/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GithubComQeeqezApiInternalVideosTypesChapterInput
 */
export interface GithubComQeeqezApiInternalVideosTypesChapterInput {
    /**
     * 
     * @type {number}
     * @memberof GithubComQeeqezApiInternalVideosTypesChapterInput
     */
    start_time_sec?: number;
    /**
     * 
     * @type {string}
     * @memberof GithubComQeeqezApiInternalVideosTypesChapterInput
     */
    title?: string;
}

/**
 * Check if a given object implements the GithubComQeeqezApiInternalVideosTypesChapterInput interface.
 */
export function instanceOfGithubComQeeqezApiInternalVideosTypesChapterInput(value: object): value is GithubComQeeqezApiInternalVideosTypesChapterInput {
    return true;
}

export function GithubComQeeqezApiInternalVideosTypesChapterInputFromJSON(json: any): GithubComQeeqezApiInternalVideosTypesChapterInput {
    return GithubComQeeqezApiInternalVideosTypesChapterInputFromJSONTyped(json, false);
}

export function GithubComQeeqezApiInternalVideosTypesChapterInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComQeeqezApiInternalVideosTypesChapterInput {
    if (json == null) {
        return json;
    }
    return {
        
        'start_time_sec': json['start_time_sec'] == null ? undefined : json['start_time_sec'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function GithubComQeeqezApiInternalVideosTypesChapterInputToJSON(json: any): GithubComQeeqezApiInternalVideosTypesChapterInput {
    return GithubComQeeqezApiInternalVideosTypesChapterInputToJSONTyped(json, false);
}

export function GithubComQeeqezApiInternalVideosTypesChapterInputToJSONTyped(value?: GithubComQeeqezApiInternalVideosTypesChapterInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_time_sec': value['start_time_sec'],
        'title': value['title'],
    };
}

