/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationPagination } from './PaginationPagination';
import {
    PaginationPaginationFromJSON,
    PaginationPaginationFromJSONTyped,
    PaginationPaginationToJSON,
    PaginationPaginationToJSONTyped,
} from './PaginationPagination';
import type { Video } from './Video';
import {
    VideoFromJSON,
    VideoFromJSONTyped,
    VideoToJSON,
    VideoToJSONTyped,
} from './Video';

/**
 * 
 * @export
 * @interface PaginationPaginatedResponseVideo
 */
export interface PaginationPaginatedResponseVideo {
    /**
     * Data contains the slice of items for the current request.
     * @type {Array<Video>}
     * @memberof PaginationPaginatedResponseVideo
     */
    data?: Array<Video>;
    /**
     * 
     * @type {PaginationPagination}
     * @memberof PaginationPaginatedResponseVideo
     */
    pagination?: PaginationPagination;
}

/**
 * Check if a given object implements the PaginationPaginatedResponseVideo interface.
 */
export function instanceOfPaginationPaginatedResponseVideo(value: object): value is PaginationPaginatedResponseVideo {
    return true;
}

export function PaginationPaginatedResponseVideoFromJSON(json: any): PaginationPaginatedResponseVideo {
    return PaginationPaginatedResponseVideoFromJSONTyped(json, false);
}

export function PaginationPaginatedResponseVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationPaginatedResponseVideo {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(VideoFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationPaginationFromJSON(json['pagination']),
    };
}

export function PaginationPaginatedResponseVideoToJSON(json: any): PaginationPaginatedResponseVideo {
    return PaginationPaginatedResponseVideoToJSONTyped(json, false);
}

export function PaginationPaginatedResponseVideoToJSONTyped(value?: PaginationPaginatedResponseVideo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(VideoToJSON)),
        'pagination': PaginationPaginationToJSON(value['pagination']),
    };
}

