/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type PostVideosUploadInitRequest
 * 
 * @export
 */
export type PostVideosUploadInitRequest = VideoUploadInitRequest | object;

export function PostVideosUploadInitRequestFromJSON(json: any): PostVideosUploadInitRequest {
    return PostVideosUploadInitRequestFromJSONTyped(json, false);
}

export function PostVideosUploadInitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostVideosUploadInitRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfVideoUploadInitRequest(json)) {
        return VideoUploadInitRequestFromJSONTyped(json, true);
    }
    return {} as any;
}

export function PostVideosUploadInitRequestToJSON(json: any): any {
    return PostVideosUploadInitRequestToJSONTyped(json, false);
}

export function PostVideosUploadInitRequestToJSONTyped(value?: PostVideosUploadInitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfVideoUploadInitRequest(value)) {
        return VideoUploadInitRequestToJSON(value as VideoUploadInitRequest);
    }
    return {};
}

