/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type VideosVideoIdChaptersPutRequest
 * 
 * @export
 */
export type VideosVideoIdChaptersPutRequest = UpdateChaptersRequest | object;

export function VideosVideoIdChaptersPutRequestFromJSON(json: any): VideosVideoIdChaptersPutRequest {
    return VideosVideoIdChaptersPutRequestFromJSONTyped(json, false);
}

export function VideosVideoIdChaptersPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideosVideoIdChaptersPutRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfUpdateChaptersRequest(json)) {
        return UpdateChaptersRequestFromJSONTyped(json, true);
    }
    return {} as any;
}

export function VideosVideoIdChaptersPutRequestToJSON(json: any): any {
    return VideosVideoIdChaptersPutRequestToJSONTyped(json, false);
}

export function VideosVideoIdChaptersPutRequestToJSONTyped(value?: VideosVideoIdChaptersPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfUpdateChaptersRequest(value)) {
        return UpdateChaptersRequestToJSON(value as UpdateChaptersRequest);
    }
    return {};
}

