/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AudioTrack
 */
export interface AudioTrack {
    /**
     * 
     * @type {string}
     * @memberof AudioTrack
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof AudioTrack
     */
    format?: string;
    /**
     * 
     * @type {string}
     * @memberof AudioTrack
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AudioTrack
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof AudioTrack
     */
    language_code?: string;
    /**
     * 
     * @type {string}
     * @memberof AudioTrack
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof AudioTrack
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof AudioTrack
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof AudioTrack
     */
    video_id?: string;
}

/**
 * Check if a given object implements the AudioTrack interface.
 */
export function instanceOfAudioTrack(value: object): value is AudioTrack {
    return true;
}

export function AudioTrackFromJSON(json: any): AudioTrack {
    return AudioTrackFromJSONTyped(json, false);
}

export function AudioTrackFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioTrack {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'format': json['format'] == null ? undefined : json['format'],
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'language_code': json['language_code'] == null ? undefined : json['language_code'],
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'url': json['url'] == null ? undefined : json['url'],
        'video_id': json['video_id'] == null ? undefined : json['video_id'],
    };
}

export function AudioTrackToJSON(json: any): AudioTrack {
    return AudioTrackToJSONTyped(json, false);
}

export function AudioTrackToJSONTyped(value?: AudioTrack | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'],
        'format': value['format'],
        'id': value['id'],
        'label': value['label'],
        'language_code': value['language_code'],
        'name': value['name'],
        'size': value['size'],
        'url': value['url'],
        'video_id': value['video_id'],
    };
}

