/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ImagesUploadInitPostRequest
 * 
 * @export
 */
export type ImagesUploadInitPostRequest = InternalImagesHandlerUploadInitRequest | object;

export function ImagesUploadInitPostRequestFromJSON(json: any): ImagesUploadInitPostRequest {
    return ImagesUploadInitPostRequestFromJSONTyped(json, false);
}

export function ImagesUploadInitPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagesUploadInitPostRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfInternalImagesHandlerUploadInitRequest(json)) {
        return InternalImagesHandlerUploadInitRequestFromJSONTyped(json, true);
    }
    return {} as any;
}

export function ImagesUploadInitPostRequestToJSON(json: any): any {
    return ImagesUploadInitPostRequestToJSONTyped(json, false);
}

export function ImagesUploadInitPostRequestToJSONTyped(value?: ImagesUploadInitPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfInternalImagesHandlerUploadInitRequest(value)) {
        return InternalImagesHandlerUploadInitRequestToJSON(value as InternalImagesHandlerUploadInitRequest);
    }
    return {};
}

