/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalImagesHandlerInitResponse
 */
export interface InternalImagesHandlerInitResponse {
    /**
     * 
     * @type {string}
     * @memberof InternalImagesHandlerInitResponse
     */
    imageId?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalImagesHandlerInitResponse
     */
    presignedUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof InternalImagesHandlerInitResponse
     */
    uploadExpires?: number;
}

/**
 * Check if a given object implements the InternalImagesHandlerInitResponse interface.
 */
export function instanceOfInternalImagesHandlerInitResponse(value: object): value is InternalImagesHandlerInitResponse {
    return true;
}

export function InternalImagesHandlerInitResponseFromJSON(json: any): InternalImagesHandlerInitResponse {
    return InternalImagesHandlerInitResponseFromJSONTyped(json, false);
}

export function InternalImagesHandlerInitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalImagesHandlerInitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'imageId': json['image_id'] == null ? undefined : json['image_id'],
        'presignedUrl': json['presigned_url'] == null ? undefined : json['presigned_url'],
        'uploadExpires': json['upload_expires'] == null ? undefined : json['upload_expires'],
    };
}

export function InternalImagesHandlerInitResponseToJSON(json: any): InternalImagesHandlerInitResponse {
    return InternalImagesHandlerInitResponseToJSONTyped(json, false);
}

export function InternalImagesHandlerInitResponseToJSONTyped(value?: InternalImagesHandlerInitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_id': value['imageId'],
        'presigned_url': value['presignedUrl'],
        'upload_expires': value['uploadExpires'],
    };
}

