/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type PostImagesUploadCompleteRequest
 * 
 * @export
 */
export type PostImagesUploadCompleteRequest = InternalImagesHandlerCompleteRequest | object;

export function PostImagesUploadCompleteRequestFromJSON(json: any): PostImagesUploadCompleteRequest {
    return PostImagesUploadCompleteRequestFromJSONTyped(json, false);
}

export function PostImagesUploadCompleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImagesUploadCompleteRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfInternalImagesHandlerCompleteRequest(json)) {
        return InternalImagesHandlerCompleteRequestFromJSONTyped(json, true);
    }
    return {} as any;
}

export function PostImagesUploadCompleteRequestToJSON(json: any): any {
    return PostImagesUploadCompleteRequestToJSONTyped(json, false);
}

export function PostImagesUploadCompleteRequestToJSONTyped(value?: PostImagesUploadCompleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfInternalImagesHandlerCompleteRequest(value)) {
        return InternalImagesHandlerCompleteRequestToJSON(value as InternalImagesHandlerCompleteRequest);
    }
    return {};
}

