/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Chapter } from './Chapter';
import {
    ChapterFromJSON,
    ChapterFromJSONTyped,
    ChapterToJSON,
    ChapterToJSONTyped,
} from './Chapter';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
    ImageToJSONTyped,
} from './Image';
import type { GithubComQeeqezApiDbSqlcPlanType } from './GithubComQeeqezApiDbSqlcPlanType';
import {
    GithubComQeeqezApiDbSqlcPlanTypeFromJSON,
    GithubComQeeqezApiDbSqlcPlanTypeFromJSONTyped,
    GithubComQeeqezApiDbSqlcPlanTypeToJSON,
    GithubComQeeqezApiDbSqlcPlanTypeToJSONTyped,
} from './GithubComQeeqezApiDbSqlcPlanType';

/**
 * 
 * @export
 * @interface Video
 */
export interface Video {
    /**
     * 
     * @type {number}
     * @memberof Video
     */
    bitrate?: number;
    /**
     * 
     * @type {Array<Chapter>}
     * @memberof Video
     */
    chapters?: Array<Chapter>;
    /**
     * 
     * @type {string}
     * @memberof Video
     */
    codec?: string;
    /**
     * 
     * @type {number}
     * @memberof Video
     */
    duration?: number;
    /**
     * 
     * @type {any}
     * @memberof Video
     */
    file?: any;
    /**
     * 
     * @type {string}
     * @memberof Video
     */
    framerate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Video
     */
    hdr?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Video
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof Video
     */
    id?: string;
    /**
     * 
     * @type {GithubComQeeqezApiDbSqlcPlanType}
     * @memberof Video
     */
    plan_type?: GithubComQeeqezApiDbSqlcPlanType;
    /**
     * 
     * @type {Image}
     * @memberof Video
     */
    poster?: Image;
    /**
     * 
     * @type {number}
     * @memberof Video
     */
    width?: number;
}



/**
 * Check if a given object implements the Video interface.
 */
export function instanceOfVideo(value: object): value is Video {
    return true;
}

export function VideoFromJSON(json: any): Video {
    return VideoFromJSONTyped(json, false);
}

export function VideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Video {
    if (json == null) {
        return json;
    }
    return {
        
        'bitrate': json['bitrate'] == null ? undefined : json['bitrate'],
        'chapters': json['chapters'] == null ? undefined : ((json['chapters'] as Array<any>).map(ChapterFromJSON)),
        'codec': json['codec'] == null ? undefined : json['codec'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'file': json['file'] == null ? undefined : json['file'],
        'framerate': json['framerate'] == null ? undefined : json['framerate'],
        'hdr': json['hdr'] == null ? undefined : json['hdr'],
        'height': json['height'] == null ? undefined : json['height'],
        'id': json['id'] == null ? undefined : json['id'],
        'plan_type': json['plan_type'] == null ? undefined : GithubComQeeqezApiDbSqlcPlanTypeFromJSON(json['plan_type']),
        'poster': json['poster'] == null ? undefined : ImageFromJSON(json['poster']),
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function VideoToJSON(json: any): Video {
    return VideoToJSONTyped(json, false);
}

export function VideoToJSONTyped(value?: Video | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bitrate': value['bitrate'],
        'chapters': value['chapters'] == null ? undefined : ((value['chapters'] as Array<any>).map(ChapterToJSON)),
        'codec': value['codec'],
        'duration': value['duration'],
        'file': value['file'],
        'framerate': value['framerate'],
        'hdr': value['hdr'],
        'height': value['height'],
        'id': value['id'],
        'plan_type': GithubComQeeqezApiDbSqlcPlanTypeToJSON(value['plan_type']),
        'poster': ImageToJSON(value['poster']),
        'width': value['width'],
    };
}

