/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GithubComQeeqezApiDbSqlcVideoQuality } from './GithubComQeeqezApiDbSqlcVideoQuality';
import {
    GithubComQeeqezApiDbSqlcVideoQualityFromJSON,
    GithubComQeeqezApiDbSqlcVideoQualityFromJSONTyped,
    GithubComQeeqezApiDbSqlcVideoQualityToJSON,
    GithubComQeeqezApiDbSqlcVideoQualityToJSONTyped,
} from './GithubComQeeqezApiDbSqlcVideoQuality';

/**
 * 
 * @export
 * @interface VideoUploadInitRequest
 */
export interface VideoUploadInitRequest {
    /**
     * 
     * @type {string}
     * @memberof VideoUploadInitRequest
     */
    file_name: string;
    /**
     * 
     * @type {string}
     * @memberof VideoUploadInitRequest
     */
    image_format?: string;
    /**
     * 
     * @type {GithubComQeeqezApiDbSqlcVideoQuality}
     * @memberof VideoUploadInitRequest
     */
    video_quality?: GithubComQeeqezApiDbSqlcVideoQuality;
}



/**
 * Check if a given object implements the VideoUploadInitRequest interface.
 */
export function instanceOfVideoUploadInitRequest(value: object): value is VideoUploadInitRequest {
    if (!('file_name' in value) || value['file_name'] === undefined) return false;
    return true;
}

export function VideoUploadInitRequestFromJSON(json: any): VideoUploadInitRequest {
    return VideoUploadInitRequestFromJSONTyped(json, false);
}

export function VideoUploadInitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoUploadInitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'file_name': json['file_name'],
        'image_format': json['image_format'] == null ? undefined : json['image_format'],
        'video_quality': json['video_quality'] == null ? undefined : GithubComQeeqezApiDbSqlcVideoQualityFromJSON(json['video_quality']),
    };
}

export function VideoUploadInitRequestToJSON(json: any): VideoUploadInitRequest {
    return VideoUploadInitRequestToJSONTyped(json, false);
}

export function VideoUploadInitRequestToJSONTyped(value?: VideoUploadInitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_name': value['file_name'],
        'image_format': value['image_format'],
        'video_quality': GithubComQeeqezApiDbSqlcVideoQualityToJSON(value['video_quality']),
    };
}

