/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Video upload completion request
 */
export interface CompleteRequest extends AdditionalDataHolder, Parsable {
    /**
     * The video_id property
     */
    videoId?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CompleteRequest}
 */
// @ts-ignore
export function createCompleteRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCompleteRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InitResponse}
 */
// @ts-ignore
export function createInitResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInitResponse;
}
/**
 * The deserialization information for the current model
 * @param CompleteRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCompleteRequest(completeRequest: Partial<CompleteRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "video_id": n => { completeRequest.videoId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param InitResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInitResponse(initResponse: Partial<InitResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "poster_id": n => { initResponse.posterId = n.getStringValue(); },
        "poster_presigned_url": n => { initResponse.posterPresignedUrl = n.getStringValue(); },
        "upload_expires": n => { initResponse.uploadExpires = n.getNumberValue(); },
        "video_id": n => { initResponse.videoId = n.getStringValue(); },
        "video_presigned_url": n => { initResponse.videoPresignedUrl = n.getStringValue(); },
    }
}
export interface InitResponse extends AdditionalDataHolder, Parsable {
    /**
     * The poster_id property
     */
    posterId?: string | null;
    /**
     * The poster_presigned_url property
     */
    posterPresignedUrl?: string | null;
    /**
     * The upload_expires property
     */
    uploadExpires?: number | null;
    /**
     * The video_id property
     */
    videoId?: string | null;
    /**
     * The video_presigned_url property
     */
    videoPresignedUrl?: string | null;
}
/**
 * Serializes information the current object
 * @param CompleteRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCompleteRequest(writer: SerializationWriter, completeRequest: Partial<CompleteRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!completeRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("video_id", completeRequest.videoId);
    writer.writeAdditionalData(completeRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param InitResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInitResponse(writer: SerializationWriter, initResponse: Partial<InitResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!initResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("poster_id", initResponse.posterId);
    writer.writeStringValue("poster_presigned_url", initResponse.posterPresignedUrl);
    writer.writeNumberValue("upload_expires", initResponse.uploadExpires);
    writer.writeStringValue("video_id", initResponse.videoId);
    writer.writeStringValue("video_presigned_url", initResponse.videoPresignedUrl);
    writer.writeAdditionalData(initResponse.additionalData);
}
/* tslint:enable */
/* eslint-enable */
