/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GithubComQeeqezApiInternalErrorsErrorResponse,
  PaginationPaginatedResponsePost,
  Post,
} from '../models/index';
import {
    GithubComQeeqezApiInternalErrorsErrorResponseFromJSON,
    GithubComQeeqezApiInternalErrorsErrorResponseToJSON,
    PaginationPaginatedResponsePostFromJSON,
    PaginationPaginatedResponsePostToJSON,
    PostFromJSON,
    PostToJSON,
} from '../models/index';

export interface FeedsFeedIdCreatorsCreatorIdGetRequest {
    feedId: string;
    creatorId: string;
    limit?: number;
    offset?: number;
}

export interface FeedsFeedIdGetRequest {
    feedId: string;
    limit?: number;
    offset?: number;
}

export interface FeedsFeedIdPostIdGetRequest {
    feedId: string;
    postId: string;
}

/**
 * 
 */
export class FeedsApi extends runtime.BaseAPI {

    /**
     * Creates request options for feedsFeedIdCreatorsCreatorIdGet without sending the request
     */
    async feedsFeedIdCreatorsCreatorIdGetRequestOpts(requestParameters: FeedsFeedIdCreatorsCreatorIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['feedId'] == null) {
            throw new runtime.RequiredError(
                'feedId',
                'Required parameter "feedId" was null or undefined when calling feedsFeedIdCreatorsCreatorIdGet().'
            );
        }

        if (requestParameters['creatorId'] == null) {
            throw new runtime.RequiredError(
                'creatorId',
                'Required parameter "creatorId" was null or undefined when calling feedsFeedIdCreatorsCreatorIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/feeds/{feedId}/creators/{creatorId}`;
        urlPath = urlPath.replace(`{${"feedId"}}`, encodeURIComponent(String(requestParameters['feedId'])));
        urlPath = urlPath.replace(`{${"creatorId"}}`, encodeURIComponent(String(requestParameters['creatorId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve posts in a feed by a specific creator, with pagination.
     * List posts by creator
     */
    async feedsFeedIdCreatorsCreatorIdGetRaw(requestParameters: FeedsFeedIdCreatorsCreatorIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationPaginatedResponsePost>> {
        const requestOptions = await this.feedsFeedIdCreatorsCreatorIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginationPaginatedResponsePostFromJSON(jsonValue));
    }

    /**
     * Retrieve posts in a feed by a specific creator, with pagination.
     * List posts by creator
     */
    async feedsFeedIdCreatorsCreatorIdGet(requestParameters: FeedsFeedIdCreatorsCreatorIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationPaginatedResponsePost> {
        const response = await this.feedsFeedIdCreatorsCreatorIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for feedsFeedIdGet without sending the request
     */
    async feedsFeedIdGetRequestOpts(requestParameters: FeedsFeedIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['feedId'] == null) {
            throw new runtime.RequiredError(
                'feedId',
                'Required parameter "feedId" was null or undefined when calling feedsFeedIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/feeds/{feedId}`;
        urlPath = urlPath.replace(`{${"feedId"}}`, encodeURIComponent(String(requestParameters['feedId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve posts in a feed, with pagination.
     * List posts in a feed
     */
    async feedsFeedIdGetRaw(requestParameters: FeedsFeedIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationPaginatedResponsePost>> {
        const requestOptions = await this.feedsFeedIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginationPaginatedResponsePostFromJSON(jsonValue));
    }

    /**
     * Retrieve posts in a feed, with pagination.
     * List posts in a feed
     */
    async feedsFeedIdGet(requestParameters: FeedsFeedIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationPaginatedResponsePost> {
        const response = await this.feedsFeedIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for feedsFeedIdPostIdGet without sending the request
     */
    async feedsFeedIdPostIdGetRequestOpts(requestParameters: FeedsFeedIdPostIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['feedId'] == null) {
            throw new runtime.RequiredError(
                'feedId',
                'Required parameter "feedId" was null or undefined when calling feedsFeedIdPostIdGet().'
            );
        }

        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling feedsFeedIdPostIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/feeds/{feedId}/{postId}`;
        urlPath = urlPath.replace(`{${"feedId"}}`, encodeURIComponent(String(requestParameters['feedId'])));
        urlPath = urlPath.replace(`{${"postId"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a post from feed by its ID
     * Get a post
     */
    async feedsFeedIdPostIdGetRaw(requestParameters: FeedsFeedIdPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>> {
        const requestOptions = await this.feedsFeedIdPostIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostFromJSON(jsonValue));
    }

    /**
     * Retrieve a post from feed by its ID
     * Get a post
     */
    async feedsFeedIdPostIdGet(requestParameters: FeedsFeedIdPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post> {
        const response = await this.feedsFeedIdPostIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
