/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GithubComQeeqezApiInternalErrorsErrorResponse,
  PaginationPaginatedResponsePost,
  Post,
} from '../models/index';
import {
    GithubComQeeqezApiInternalErrorsErrorResponseFromJSON,
    GithubComQeeqezApiInternalErrorsErrorResponseToJSON,
    PaginationPaginatedResponsePostFromJSON,
    PaginationPaginatedResponsePostToJSON,
    PostFromJSON,
    PostToJSON,
} from '../models/index';

export interface GetFeedsFeedIdRequest {
    feedId: string;
    limit?: number;
    offset?: number;
}

export interface GetFeedsFeedIdCreatorsCreatorIdRequest {
    feedId: string;
    creatorId: string;
    limit?: number;
    offset?: number;
}

export interface GetFeedsFeedIdPostIdRequest {
    feedId: string;
    postId: string;
}

/**
 * FeedsApi - interface
 * 
 * @export
 * @interface FeedsApiInterface
 */
export interface FeedsApiInterface {
    /**
     * Creates request options for getFeedsFeedId without sending the request
     * @param {string} feedId Feed ID
     * @param {number} [limit] Maximum number of items to return in a single request. &lt;br&gt; **Default:** &#x60;25&#x60;
     * @param {number} [offset] Starting point of the result set. &lt;br&gt;To get page 2 with a limit of 25, set &#x60;offset&#x60; to &#x60;25&#x60;. &lt;br&gt; **Default:** &#x60;0&#x60;
     * @throws {RequiredError}
     * @memberof FeedsApiInterface
     */
    getFeedsFeedIdRequestOpts(requestParameters: GetFeedsFeedIdRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieve posts in a feed, with pagination.
     * @summary List posts in a feed
     * @param {string} feedId Feed ID
     * @param {number} [limit] Maximum number of items to return in a single request. &lt;br&gt; **Default:** &#x60;25&#x60;
     * @param {number} [offset] Starting point of the result set. &lt;br&gt;To get page 2 with a limit of 25, set &#x60;offset&#x60; to &#x60;25&#x60;. &lt;br&gt; **Default:** &#x60;0&#x60;
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedsApiInterface
     */
    getFeedsFeedIdRaw(requestParameters: GetFeedsFeedIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationPaginatedResponsePost>>;

    /**
     * Retrieve posts in a feed, with pagination.
     * List posts in a feed
     */
    getFeedsFeedId(requestParameters: GetFeedsFeedIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationPaginatedResponsePost>;

    /**
     * Creates request options for getFeedsFeedIdCreatorsCreatorId without sending the request
     * @param {string} feedId Feed ID
     * @param {string} creatorId Creator ID
     * @param {number} [limit] Maximum number of items to return in a single request. &lt;br&gt; **Default:** &#x60;25&#x60;
     * @param {number} [offset] Starting point of the result set. &lt;br&gt;To get page 2 with a limit of 25, set &#x60;offset&#x60; to &#x60;25&#x60;. &lt;br&gt; **Default:** &#x60;0&#x60;
     * @throws {RequiredError}
     * @memberof FeedsApiInterface
     */
    getFeedsFeedIdCreatorsCreatorIdRequestOpts(requestParameters: GetFeedsFeedIdCreatorsCreatorIdRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieve posts in a feed by a specific creator, with pagination.
     * @summary List posts by creator
     * @param {string} feedId Feed ID
     * @param {string} creatorId Creator ID
     * @param {number} [limit] Maximum number of items to return in a single request. &lt;br&gt; **Default:** &#x60;25&#x60;
     * @param {number} [offset] Starting point of the result set. &lt;br&gt;To get page 2 with a limit of 25, set &#x60;offset&#x60; to &#x60;25&#x60;. &lt;br&gt; **Default:** &#x60;0&#x60;
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedsApiInterface
     */
    getFeedsFeedIdCreatorsCreatorIdRaw(requestParameters: GetFeedsFeedIdCreatorsCreatorIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationPaginatedResponsePost>>;

    /**
     * Retrieve posts in a feed by a specific creator, with pagination.
     * List posts by creator
     */
    getFeedsFeedIdCreatorsCreatorId(requestParameters: GetFeedsFeedIdCreatorsCreatorIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationPaginatedResponsePost>;

    /**
     * Creates request options for getFeedsFeedIdPostId without sending the request
     * @param {string} feedId Feed ID
     * @param {string} postId Post ID
     * @throws {RequiredError}
     * @memberof FeedsApiInterface
     */
    getFeedsFeedIdPostIdRequestOpts(requestParameters: GetFeedsFeedIdPostIdRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieve a post from feed by its ID
     * @summary Get a post
     * @param {string} feedId Feed ID
     * @param {string} postId Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedsApiInterface
     */
    getFeedsFeedIdPostIdRaw(requestParameters: GetFeedsFeedIdPostIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>>;

    /**
     * Retrieve a post from feed by its ID
     * Get a post
     */
    getFeedsFeedIdPostId(requestParameters: GetFeedsFeedIdPostIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post>;

}

/**
 * 
 */
export class FeedsApi extends runtime.BaseAPI implements FeedsApiInterface {

    /**
     * Creates request options for getFeedsFeedId without sending the request
     */
    async getFeedsFeedIdRequestOpts(requestParameters: GetFeedsFeedIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['feedId'] == null) {
            throw new runtime.RequiredError(
                'feedId',
                'Required parameter "feedId" was null or undefined when calling getFeedsFeedId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/feeds/{feedId}`;
        urlPath = urlPath.replace(`{${"feedId"}}`, encodeURIComponent(String(requestParameters['feedId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve posts in a feed, with pagination.
     * List posts in a feed
     */
    async getFeedsFeedIdRaw(requestParameters: GetFeedsFeedIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationPaginatedResponsePost>> {
        const requestOptions = await this.getFeedsFeedIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginationPaginatedResponsePostFromJSON(jsonValue));
    }

    /**
     * Retrieve posts in a feed, with pagination.
     * List posts in a feed
     */
    async getFeedsFeedId(requestParameters: GetFeedsFeedIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationPaginatedResponsePost> {
        const response = await this.getFeedsFeedIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeedsFeedIdCreatorsCreatorId without sending the request
     */
    async getFeedsFeedIdCreatorsCreatorIdRequestOpts(requestParameters: GetFeedsFeedIdCreatorsCreatorIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['feedId'] == null) {
            throw new runtime.RequiredError(
                'feedId',
                'Required parameter "feedId" was null or undefined when calling getFeedsFeedIdCreatorsCreatorId().'
            );
        }

        if (requestParameters['creatorId'] == null) {
            throw new runtime.RequiredError(
                'creatorId',
                'Required parameter "creatorId" was null or undefined when calling getFeedsFeedIdCreatorsCreatorId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/feeds/{feedId}/creators/{creatorId}`;
        urlPath = urlPath.replace(`{${"feedId"}}`, encodeURIComponent(String(requestParameters['feedId'])));
        urlPath = urlPath.replace(`{${"creatorId"}}`, encodeURIComponent(String(requestParameters['creatorId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve posts in a feed by a specific creator, with pagination.
     * List posts by creator
     */
    async getFeedsFeedIdCreatorsCreatorIdRaw(requestParameters: GetFeedsFeedIdCreatorsCreatorIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationPaginatedResponsePost>> {
        const requestOptions = await this.getFeedsFeedIdCreatorsCreatorIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginationPaginatedResponsePostFromJSON(jsonValue));
    }

    /**
     * Retrieve posts in a feed by a specific creator, with pagination.
     * List posts by creator
     */
    async getFeedsFeedIdCreatorsCreatorId(requestParameters: GetFeedsFeedIdCreatorsCreatorIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationPaginatedResponsePost> {
        const response = await this.getFeedsFeedIdCreatorsCreatorIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFeedsFeedIdPostId without sending the request
     */
    async getFeedsFeedIdPostIdRequestOpts(requestParameters: GetFeedsFeedIdPostIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['feedId'] == null) {
            throw new runtime.RequiredError(
                'feedId',
                'Required parameter "feedId" was null or undefined when calling getFeedsFeedIdPostId().'
            );
        }

        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling getFeedsFeedIdPostId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/feeds/{feedId}/{postId}`;
        urlPath = urlPath.replace(`{${"feedId"}}`, encodeURIComponent(String(requestParameters['feedId'])));
        urlPath = urlPath.replace(`{${"postId"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a post from feed by its ID
     * Get a post
     */
    async getFeedsFeedIdPostIdRaw(requestParameters: GetFeedsFeedIdPostIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Post>> {
        const requestOptions = await this.getFeedsFeedIdPostIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostFromJSON(jsonValue));
    }

    /**
     * Retrieve a post from feed by its ID
     * Get a post
     */
    async getFeedsFeedIdPostId(requestParameters: GetFeedsFeedIdPostIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Post> {
        const response = await this.getFeedsFeedIdPostIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
