/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, type ErrorResponse } from '../../../models/github_com_qeeqez_api_internal_errors/index.js';
// @ts-ignore
import { createInitResponseFromDiscriminatorValue, serializeInitResponse, type InitResponse } from '../../../models/github_com_qeeqez_api_internal_videos_handler_upload/index.js';
// @ts-ignore
import { serializeVideoUploadInitRequest, type VideoUploadInitRequest } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /videos/upload/init
 */
export interface InitRequestBuilder extends BaseRequestBuilder<InitRequestBuilder> {
    /**
     * Initialize a video upload and get presigned URLs for video and poster using API key authentication
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InitResponse>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     * @throws {ErrorResponse} error when the service returns a 500 status code
     */
     post(body: VideoUploadInitRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InitResponse | undefined>;
    /**
     * Initialize a video upload and get presigned URLs for video and poster using API key authentication
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: VideoUploadInitRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InitRequestBuilderUriTemplate = "{+baseurl}/videos/upload/init";
/**
 * Metadata for all the requests in the request builder.
 */
export const InitRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: InitRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInitResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeVideoUploadInitRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
