/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Upload completion request
 */
export interface CompleteRequest extends AdditionalDataHolder, Parsable {
    /**
     * The attached_to_video property
     */
    attachedToVideo?: boolean | null;
    /**
     * The image_id property
     */
    imageId?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CompleteRequest}
 */
// @ts-ignore
export function createCompleteRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCompleteRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InitResponse}
 */
// @ts-ignore
export function createInitResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInitResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UploadInitRequest}
 */
// @ts-ignore
export function createUploadInitRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUploadInitRequest;
}
/**
 * The deserialization information for the current model
 * @param CompleteRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCompleteRequest(completeRequest: Partial<CompleteRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "attached_to_video": n => { completeRequest.attachedToVideo = n.getBooleanValue(); },
        "image_id": n => { completeRequest.imageId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param InitResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInitResponse(initResponse: Partial<InitResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "image_id": n => { initResponse.imageId = n.getStringValue(); },
        "presigned_url": n => { initResponse.presignedUrl = n.getStringValue(); },
        "upload_expires": n => { initResponse.uploadExpires = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UploadInitRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUploadInitRequest(uploadInitRequest: Partial<UploadInitRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "format": n => { uploadInitRequest.format = n.getStringValue(); },
        "name": n => { uploadInitRequest.name = n.getStringValue(); },
    }
}
export interface InitResponse extends AdditionalDataHolder, Parsable {
    /**
     * The image_id property
     */
    imageId?: string | null;
    /**
     * The presigned_url property
     */
    presignedUrl?: string | null;
    /**
     * The upload_expires property
     */
    uploadExpires?: number | null;
}
/**
 * Serializes information the current object
 * @param CompleteRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCompleteRequest(writer: SerializationWriter, completeRequest: Partial<CompleteRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!completeRequest || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("attached_to_video", completeRequest.attachedToVideo);
    writer.writeStringValue("image_id", completeRequest.imageId);
    writer.writeAdditionalData(completeRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param InitResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInitResponse(writer: SerializationWriter, initResponse: Partial<InitResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!initResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("image_id", initResponse.imageId);
    writer.writeStringValue("presigned_url", initResponse.presignedUrl);
    writer.writeNumberValue("upload_expires", initResponse.uploadExpires);
    writer.writeAdditionalData(initResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UploadInitRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUploadInitRequest(writer: SerializationWriter, uploadInitRequest: Partial<UploadInitRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!uploadInitRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("format", uploadInitRequest.format);
    writer.writeStringValue("name", uploadInitRequest.name);
    writer.writeAdditionalData(uploadInitRequest.additionalData);
}
/**
 * Upload initialization request
 */
export interface UploadInitRequest extends AdditionalDataHolder, Parsable {
    /**
     * The format property
     */
    format?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
/* tslint:enable */
/* eslint-enable */
