/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FileStatus = {
    FileStatusUploading: 'uploading',
    FileStatusUploaded: 'uploaded',
    FileStatusProcessing: 'processing',
    FileStatusPreparing: 'preparing',
    FileStatusReady: 'ready',
    FileStatusError: 'error'
} as const;
export type FileStatus = typeof FileStatus[keyof typeof FileStatus];


export function instanceOfFileStatus(value: any): boolean {
    for (const key in FileStatus) {
        if (Object.prototype.hasOwnProperty.call(FileStatus, key)) {
            if (FileStatus[key as keyof typeof FileStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FileStatusFromJSON(json: any): FileStatus {
    return FileStatusFromJSONTyped(json, false);
}

export function FileStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileStatus {
    return json as FileStatus;
}

export function FileStatusToJSON(value?: FileStatus | null): any {
    return value as any;
}

export function FileStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): FileStatus {
    return value as FileStatus;
}

