/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GithubComQeeqezApiDbSqlcPlanType = {
    PlanTypeFree: 'free',
    PlanTypePro: 'pro',
    PlanTypeCustom: 'custom',
    PlanTypePayAsYouGo: 'pay_as_you_go'
} as const;
export type GithubComQeeqezApiDbSqlcPlanType = typeof GithubComQeeqezApiDbSqlcPlanType[keyof typeof GithubComQeeqezApiDbSqlcPlanType];


export function instanceOfGithubComQeeqezApiDbSqlcPlanType(value: any): boolean {
    for (const key in GithubComQeeqezApiDbSqlcPlanType) {
        if (Object.prototype.hasOwnProperty.call(GithubComQeeqezApiDbSqlcPlanType, key)) {
            if (GithubComQeeqezApiDbSqlcPlanType[key as keyof typeof GithubComQeeqezApiDbSqlcPlanType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GithubComQeeqezApiDbSqlcPlanTypeFromJSON(json: any): GithubComQeeqezApiDbSqlcPlanType {
    return GithubComQeeqezApiDbSqlcPlanTypeFromJSONTyped(json, false);
}

export function GithubComQeeqezApiDbSqlcPlanTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComQeeqezApiDbSqlcPlanType {
    return json as GithubComQeeqezApiDbSqlcPlanType;
}

export function GithubComQeeqezApiDbSqlcPlanTypeToJSON(value?: GithubComQeeqezApiDbSqlcPlanType | null): any {
    return value as any;
}

export function GithubComQeeqezApiDbSqlcPlanTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): GithubComQeeqezApiDbSqlcPlanType {
    return value as GithubComQeeqezApiDbSqlcPlanType;
}

