/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Chapter } from './Chapter';
import {
    ChapterFromJSON,
    ChapterFromJSONTyped,
    ChapterToJSON,
    ChapterToJSONTyped,
} from './Chapter';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
    ImageToJSONTyped,
} from './Image';
import type { GithubComQeeqezApiDbSqlcPlanType } from './GithubComQeeqezApiDbSqlcPlanType';
import {
    GithubComQeeqezApiDbSqlcPlanTypeFromJSON,
    GithubComQeeqezApiDbSqlcPlanTypeFromJSONTyped,
    GithubComQeeqezApiDbSqlcPlanTypeToJSON,
    GithubComQeeqezApiDbSqlcPlanTypeToJSONTyped,
} from './GithubComQeeqezApiDbSqlcPlanType';

/**
 * 
 * @export
 * @interface GithubComQeeqezApiInternalVideosVideoResponse
 */
export interface GithubComQeeqezApiInternalVideosVideoResponse {
    /**
     * 
     * @type {number}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    bitrate?: number;
    /**
     * 
     * @type {Array<Chapter>}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    chapters?: Array<Chapter>;
    /**
     * 
     * @type {string}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    codec?: string;
    /**
     * 
     * @type {number}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    duration?: number;
    /**
     * 
     * @type {any}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    file?: any;
    /**
     * 
     * @type {string}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    framerate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    hdr?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    id?: string;
    /**
     * 
     * @type {GithubComQeeqezApiDbSqlcPlanType}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    plan_type?: GithubComQeeqezApiDbSqlcPlanType;
    /**
     * 
     * @type {Image}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    poster?: Image;
    /**
     * 
     * @type {number}
     * @memberof GithubComQeeqezApiInternalVideosVideoResponse
     */
    width?: number;
}



/**
 * Check if a given object implements the GithubComQeeqezApiInternalVideosVideoResponse interface.
 */
export function instanceOfGithubComQeeqezApiInternalVideosVideoResponse(value: object): value is GithubComQeeqezApiInternalVideosVideoResponse {
    return true;
}

export function GithubComQeeqezApiInternalVideosVideoResponseFromJSON(json: any): GithubComQeeqezApiInternalVideosVideoResponse {
    return GithubComQeeqezApiInternalVideosVideoResponseFromJSONTyped(json, false);
}

export function GithubComQeeqezApiInternalVideosVideoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComQeeqezApiInternalVideosVideoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bitrate': json['bitrate'] == null ? undefined : json['bitrate'],
        'chapters': json['chapters'] == null ? undefined : ((json['chapters'] as Array<any>).map(ChapterFromJSON)),
        'codec': json['codec'] == null ? undefined : json['codec'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'file': json['file'] == null ? undefined : json['file'],
        'framerate': json['framerate'] == null ? undefined : json['framerate'],
        'hdr': json['hdr'] == null ? undefined : json['hdr'],
        'height': json['height'] == null ? undefined : json['height'],
        'id': json['id'] == null ? undefined : json['id'],
        'plan_type': json['plan_type'] == null ? undefined : GithubComQeeqezApiDbSqlcPlanTypeFromJSON(json['plan_type']),
        'poster': json['poster'] == null ? undefined : ImageFromJSON(json['poster']),
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function GithubComQeeqezApiInternalVideosVideoResponseToJSON(json: any): GithubComQeeqezApiInternalVideosVideoResponse {
    return GithubComQeeqezApiInternalVideosVideoResponseToJSONTyped(json, false);
}

export function GithubComQeeqezApiInternalVideosVideoResponseToJSONTyped(value?: GithubComQeeqezApiInternalVideosVideoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bitrate': value['bitrate'],
        'chapters': value['chapters'] == null ? undefined : ((value['chapters'] as Array<any>).map(ChapterToJSON)),
        'codec': value['codec'],
        'duration': value['duration'],
        'file': value['file'],
        'framerate': value['framerate'],
        'hdr': value['hdr'],
        'height': value['height'],
        'id': value['id'],
        'plan_type': GithubComQeeqezApiDbSqlcPlanTypeToJSON(value['plan_type']),
        'poster': ImageToJSON(value['poster']),
        'width': value['width'],
    };
}

