/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileStatus } from './FileStatus';
import {
    FileStatusFromJSON,
    FileStatusFromJSONTyped,
    FileStatusToJSON,
    FileStatusToJSONTyped,
} from './FileStatus';

/**
 * 
 * @export
 * @interface ModelFile
 */
export interface ModelFile {
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    format?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    project_id?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelFile
     */
    size?: number;
    /**
     * 
     * @type {FileStatus}
     * @memberof ModelFile
     */
    status?: FileStatus;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    updated_at?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelFile
     */
    url?: string;
}



/**
 * Check if a given object implements the ModelFile interface.
 */
export function instanceOfModelFile(value: object): value is ModelFile {
    return true;
}

export function ModelFileFromJSON(json: any): ModelFile {
    return ModelFileFromJSONTyped(json, false);
}

export function ModelFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelFile {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'format': json['format'] == null ? undefined : json['format'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'project_id': json['project_id'] == null ? undefined : json['project_id'],
        'size': json['size'] == null ? undefined : json['size'],
        'status': json['status'] == null ? undefined : FileStatusFromJSON(json['status']),
        'updated_at': json['updated_at'] == null ? undefined : json['updated_at'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ModelFileToJSON(json: any): ModelFile {
    return ModelFileToJSONTyped(json, false);
}

export function ModelFileToJSONTyped(value?: ModelFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['created_at'],
        'format': value['format'],
        'id': value['id'],
        'name': value['name'],
        'project_id': value['project_id'],
        'size': value['size'],
        'status': FileStatusToJSON(value['status']),
        'updated_at': value['updated_at'],
        'url': value['url'],
    };
}

