/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PostType = {
    PostTypeImage: 'image',
    PostTypeVideo: 'video',
    Video2: 'video',
    Image2: 'image'
} as const;
export type PostType = typeof PostType[keyof typeof PostType];


export function instanceOfPostType(value: any): boolean {
    for (const key in PostType) {
        if (Object.prototype.hasOwnProperty.call(PostType, key)) {
            if (PostType[key as keyof typeof PostType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PostTypeFromJSON(json: any): PostType {
    return PostTypeFromJSONTyped(json, false);
}

export function PostTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostType {
    return json as PostType;
}

export function PostTypeToJSON(value?: PostType | null): any {
    return value as any;
}

export function PostTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PostType {
    return value as PostType;
}

