/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubtitleDelete
 */
export interface SubtitleDelete {
    /**
     * 
     * @type {string}
     * @memberof SubtitleDelete
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof SubtitleDelete
     */
    status?: string;
}

/**
 * Check if a given object implements the SubtitleDelete interface.
 */
export function instanceOfSubtitleDelete(value: object): value is SubtitleDelete {
    return true;
}

export function SubtitleDeleteFromJSON(json: any): SubtitleDelete {
    return SubtitleDeleteFromJSONTyped(json, false);
}

export function SubtitleDeleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubtitleDelete {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function SubtitleDeleteToJSON(json: any): SubtitleDelete {
    return SubtitleDeleteToJSONTyped(json, false);
}

export function SubtitleDeleteToJSONTyped(value?: SubtitleDelete | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'status': value['status'],
    };
}

