/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GithubComQeeqezApiInternalVideosTypesChapterInput } from './GithubComQeeqezApiInternalVideosTypesChapterInput';
import {
    GithubComQeeqezApiInternalVideosTypesChapterInputFromJSON,
    GithubComQeeqezApiInternalVideosTypesChapterInputFromJSONTyped,
    GithubComQeeqezApiInternalVideosTypesChapterInputToJSON,
    GithubComQeeqezApiInternalVideosTypesChapterInputToJSONTyped,
} from './GithubComQeeqezApiInternalVideosTypesChapterInput';

/**
 * 
 * @export
 * @interface UpdateChaptersRequest
 */
export interface UpdateChaptersRequest {
    /**
     * 
     * @type {Array<GithubComQeeqezApiInternalVideosTypesChapterInput>}
     * @memberof UpdateChaptersRequest
     */
    chapters?: Array<GithubComQeeqezApiInternalVideosTypesChapterInput>;
}

/**
 * Check if a given object implements the UpdateChaptersRequest interface.
 */
export function instanceOfUpdateChaptersRequest(value: object): value is UpdateChaptersRequest {
    return true;
}

export function UpdateChaptersRequestFromJSON(json: any): UpdateChaptersRequest {
    return UpdateChaptersRequestFromJSONTyped(json, false);
}

export function UpdateChaptersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateChaptersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapters': json['chapters'] == null ? undefined : ((json['chapters'] as Array<any>).map(GithubComQeeqezApiInternalVideosTypesChapterInputFromJSON)),
    };
}

export function UpdateChaptersRequestToJSON(json: any): UpdateChaptersRequest {
    return UpdateChaptersRequestToJSONTyped(json, false);
}

export function UpdateChaptersRequestToJSONTyped(value?: UpdateChaptersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapters': value['chapters'] == null ? undefined : ((value['chapters'] as Array<any>).map(GithubComQeeqezApiInternalVideosTypesChapterInputToJSON)),
    };
}

