/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorResponse}
 */
// @ts-ignore
export function createErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorResponse;
}
/**
 * The deserialization information for the current model
 * @param ErrorResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorResponse(errorResponse: Partial<ErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { errorResponse.code = n.getNumberValue(); },
        "details": n => { errorResponse.details = n.getStringValue(); },
        "error": n => { errorResponse.errorEscaped = n.getStringValue(); },
    }
}
/**
 * Standard error response returned by the API
 */
export interface ErrorResponse extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * HTTP status code
     */
    code?: number | null;
    /**
     * Optional details about the error
     */
    details?: string | null;
    /**
     * Error message describing what went wrong
     */
    errorEscaped?: string | null;
}
/**
 * Serializes information the current object
 * @param ErrorResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorResponse(writer: SerializationWriter, errorResponse: Partial<ErrorResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorResponse || isSerializingDerivedType) { return; }
    writer.writeNumberValue("code", errorResponse.code);
    writer.writeStringValue("details", errorResponse.details);
    writer.writeStringValue("error", errorResponse.errorEscaped);
    writer.writeAdditionalData(errorResponse.additionalData);
}
/* tslint:enable */
/* eslint-enable */
