/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, type ErrorResponse } from '../../../models/github_com_qeeqez_api_internal_errors/index.js';
// @ts-ignore
import { createVideoFromDiscriminatorValue, serializeVideo, type Video } from '../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ThumbnailPutRequestBody}
 */
// @ts-ignore
export function createThumbnailPutRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoThumbnailPutRequestBody;
}
/**
 * The deserialization information for the current model
 * @param ThumbnailPutRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoThumbnailPutRequestBody(thumbnailPutRequestBody: Partial<ThumbnailPutRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "thumbnail": n => { thumbnailPutRequestBody.thumbnail = n.getByteArrayValue(); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ThumbnailPutRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeThumbnailPutRequestBody(writer: SerializationWriter, thumbnailPutRequestBody: Partial<ThumbnailPutRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!thumbnailPutRequestBody || isSerializingDerivedType) { return; }
    writer.writeByteArrayValue("thumbnail", thumbnailPutRequestBody.thumbnail);
    writer.writeAdditionalData(thumbnailPutRequestBody.additionalData);
}
export interface ThumbnailPutRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The thumbnail property
     */
    thumbnail?: ArrayBuffer | null;
}
/**
 * Builds and executes requests for operations under /videos/{videoId}/thumbnail
 */
export interface ThumbnailRequestBuilder extends BaseRequestBuilder<ThumbnailRequestBuilder> {
    /**
     * Update the thumbnail image for an existing video using API key authentication
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Video>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     * @throws {ErrorResponse} error when the service returns a 404 status code
     * @throws {ErrorResponse} error when the service returns a 500 status code
     */
     put(body: ThumbnailPutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Video | undefined>;
    /**
     * Update the thumbnail image for an existing video using API key authentication
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: ThumbnailPutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ThumbnailRequestBuilderUriTemplate = "{+baseurl}/videos/{videoId}/thumbnail";
/**
 * Metadata for all the requests in the request builder.
 */
export const ThumbnailRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: ThumbnailRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createVideoFromDiscriminatorValue,
        requestBodyContentType: "application/x-www-form-urlencoded",
        requestBodySerializer: serializeThumbnailPutRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
