/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSubtitleDeleteFromDiscriminatorValue, type SubtitleDelete } from '../../../models/index.js';
// @ts-ignore
import { type WithLang_codeItemRequestBuilder, WithLang_codeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /videos/{videoId}/subtitles
 */
export interface SubtitlesRequestBuilder extends BaseRequestBuilder<SubtitlesRequestBuilder> {
    /**
     * Gets an item from the rixlSdk.videos.item.subtitles.item collection
     * @param lang_code Language Code (BCP 47)
     * @returns {WithLang_codeItemRequestBuilder}
     */
     byLang_code(lang_code: string) : WithLang_codeItemRequestBuilder;
    /**
     * Remove all subtitles from a video using API key authentication
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SubtitleDelete>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SubtitleDelete | undefined>;
    /**
     * Remove all subtitles from a video using API key authentication
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SubtitlesRequestBuilderUriTemplate = "{+baseurl}/videos/{videoId}/subtitles";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SubtitlesRequestBuilderNavigationMetadata: Record<Exclude<keyof SubtitlesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byLang_code: {
        requestsMetadata: WithLang_codeItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["lang_code"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SubtitlesRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: SubtitlesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSubtitleDeleteFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
