/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSubtitleDeleteFromDiscriminatorValue, createSubtitleFromDiscriminatorValue, serializeSubtitle, type Subtitle, type SubtitleDelete } from '../../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithLang_codePutRequestBody}
 */
// @ts-ignore
export function createWithLang_codePutRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithLang_codePutRequestBody;
}
/**
 * The deserialization information for the current model
 * @param WithLang_codePutRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithLang_codePutRequestBody(withLang_codePutRequestBody: Partial<WithLang_codePutRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "file": n => { withLang_codePutRequestBody.file = n.getByteArrayValue(); },
        "label": n => { withLang_codePutRequestBody.label = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithLang_codePutRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithLang_codePutRequestBody(writer: SerializationWriter, withLang_codePutRequestBody: Partial<WithLang_codePutRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withLang_codePutRequestBody || isSerializingDerivedType) { return; }
    writer.writeByteArrayValue("file", withLang_codePutRequestBody.file);
    writer.writeStringValue("label", withLang_codePutRequestBody.label);
    writer.writeAdditionalData(withLang_codePutRequestBody.additionalData);
}
/**
 * Builds and executes requests for operations under /videos/{videoId}/subtitles/{lang_code}
 */
export interface WithLang_codeItemRequestBuilder extends BaseRequestBuilder<WithLang_codeItemRequestBuilder> {
    /**
     * Remove a subtitle for a specific language using API key authentication
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SubtitleDelete>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SubtitleDelete | undefined>;
    /**
     * Add or replace a subtitle for a specific language using API key authentication
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Subtitle>}
     */
     put(body: WithLang_codePutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Subtitle | undefined>;
    /**
     * Remove a subtitle for a specific language using API key authentication
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Add or replace a subtitle for a specific language using API key authentication
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: WithLang_codePutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface WithLang_codePutRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The file property
     */
    file?: ArrayBuffer | null;
    /**
     * The label property
     */
    label?: string | null;
}
/**
 * Uri template for the request builder.
 */
export const WithLang_codeItemRequestBuilderUriTemplate = "{+baseurl}/videos/{videoId}/subtitles/{lang_code}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithLang_codeItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithLang_codeItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSubtitleDeleteFromDiscriminatorValue,
    },
    put: {
        uriTemplate: WithLang_codeItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createSubtitleFromDiscriminatorValue,
        requestBodyContentType: "application/x-www-form-urlencoded",
        requestBodySerializer: serializeWithLang_codePutRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
