/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createImageFromDiscriminatorValue, createPostFromDiscriminatorValue, createVideoFromDiscriminatorValue, serializeImage, serializePost, serializeVideo, type Image, type Post, type Video } from '../index.js';
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaginatedResponseImage}
 */
// @ts-ignore
export function createPaginatedResponseImageFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaginatedResponseImage;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaginatedResponsePost}
 */
// @ts-ignore
export function createPaginatedResponsePostFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaginatedResponsePost;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaginatedResponseVideo}
 */
// @ts-ignore
export function createPaginatedResponseVideoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaginatedResponseVideo;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Pagination}
 */
// @ts-ignore
export function createPaginationFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPagination;
}
/**
 * The deserialization information for the current model
 * @param PaginatedResponseImage The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaginatedResponseImage(paginatedResponseImage: Partial<PaginatedResponseImage> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { paginatedResponseImage.data = n.getCollectionOfObjectValues<Image>(createImageFromDiscriminatorValue); },
        "pagination": n => { paginatedResponseImage.pagination = n.getObjectValue<Pagination>(createPaginationFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PaginatedResponsePost The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaginatedResponsePost(paginatedResponsePost: Partial<PaginatedResponsePost> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { paginatedResponsePost.data = n.getCollectionOfObjectValues<Post>(createPostFromDiscriminatorValue); },
        "pagination": n => { paginatedResponsePost.pagination = n.getObjectValue<Pagination>(createPaginationFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PaginatedResponseVideo The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaginatedResponseVideo(paginatedResponseVideo: Partial<PaginatedResponseVideo> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { paginatedResponseVideo.data = n.getCollectionOfObjectValues<Video>(createVideoFromDiscriminatorValue); },
        "pagination": n => { paginatedResponseVideo.pagination = n.getObjectValue<Pagination>(createPaginationFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param Pagination The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPagination(pagination: Partial<Pagination> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "limit": n => { pagination.limit = n.getNumberValue(); },
        "offset": n => { pagination.offset = n.getNumberValue(); },
        "total": n => { pagination.total = n.getNumberValue(); },
    }
}
export interface PaginatedResponseImage extends AdditionalDataHolder, Parsable {
    /**
     * Data contains the slice of items for the current request.
     */
    data?: Image[] | null;
    /**
     * Pagination data for the request.
     */
    pagination?: Pagination | null;
}
export interface PaginatedResponsePost extends AdditionalDataHolder, Parsable {
    /**
     * Data contains the slice of items for the current request.
     */
    data?: Post[] | null;
    /**
     * Pagination data for the request.
     */
    pagination?: Pagination | null;
}
export interface PaginatedResponseVideo extends AdditionalDataHolder, Parsable {
    /**
     * Data contains the slice of items for the current request.
     */
    data?: Video[] | null;
    /**
     * Pagination data for the request.
     */
    pagination?: Pagination | null;
}
/**
 * Pagination data for the request.
 */
export interface Pagination extends AdditionalDataHolder, Parsable {
    /**
     * Maximum number of items to return in a single request.
     */
    limit?: number | null;
    /**
     * Starting point of the result set.
     */
    offset?: number | null;
    /**
     * The total number of available items in the full list.
     */
    total?: number | null;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaginatedResponseImage The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaginatedResponseImage(writer: SerializationWriter, paginatedResponseImage: Partial<PaginatedResponseImage> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paginatedResponseImage || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Image>("data", paginatedResponseImage.data, serializeImage);
    writer.writeObjectValue<Pagination>("pagination", paginatedResponseImage.pagination, serializePagination);
    writer.writeAdditionalData(paginatedResponseImage.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaginatedResponsePost The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaginatedResponsePost(writer: SerializationWriter, paginatedResponsePost: Partial<PaginatedResponsePost> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paginatedResponsePost || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Post>("data", paginatedResponsePost.data, serializePost);
    writer.writeObjectValue<Pagination>("pagination", paginatedResponsePost.pagination, serializePagination);
    writer.writeAdditionalData(paginatedResponsePost.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PaginatedResponseVideo The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaginatedResponseVideo(writer: SerializationWriter, paginatedResponseVideo: Partial<PaginatedResponseVideo> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!paginatedResponseVideo || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Video>("data", paginatedResponseVideo.data, serializeVideo);
    writer.writeObjectValue<Pagination>("pagination", paginatedResponseVideo.pagination, serializePagination);
    writer.writeAdditionalData(paginatedResponseVideo.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Pagination The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePagination(writer: SerializationWriter, pagination: Partial<Pagination> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!pagination || isSerializingDerivedType) { return; }
    writer.writeNumberValue("limit", pagination.limit);
    writer.writeNumberValue("offset", pagination.offset);
    writer.writeNumberValue("total", pagination.total);
    writer.writeAdditionalData(pagination.additionalData);
}
/* tslint:enable */
/* eslint-enable */
