/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AudioTrack,
  AudioTrackDelete,
  GithubComQeeqezApiInternalErrorsErrorResponse,
  GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest,
  GithubComQeeqezApiInternalVideosHandlerUploadInitResponse,
  InternalVideosHandlerSubtitlesLanguageResponse,
  PaginationPaginatedResponseVideo,
  Subtitle,
  SubtitleDelete,
  UpdateChaptersRequest,
  UpdateChaptersResponse,
  Video,
  VideoUploadInitRequest,
} from '../models/index';
import {
    AudioTrackFromJSON,
    AudioTrackToJSON,
    AudioTrackDeleteFromJSON,
    AudioTrackDeleteToJSON,
    GithubComQeeqezApiInternalErrorsErrorResponseFromJSON,
    GithubComQeeqezApiInternalErrorsErrorResponseToJSON,
    GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequestFromJSON,
    GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequestToJSON,
    GithubComQeeqezApiInternalVideosHandlerUploadInitResponseFromJSON,
    GithubComQeeqezApiInternalVideosHandlerUploadInitResponseToJSON,
    InternalVideosHandlerSubtitlesLanguageResponseFromJSON,
    InternalVideosHandlerSubtitlesLanguageResponseToJSON,
    PaginationPaginatedResponseVideoFromJSON,
    PaginationPaginatedResponseVideoToJSON,
    SubtitleFromJSON,
    SubtitleToJSON,
    SubtitleDeleteFromJSON,
    SubtitleDeleteToJSON,
    UpdateChaptersRequestFromJSON,
    UpdateChaptersRequestToJSON,
    UpdateChaptersResponseFromJSON,
    UpdateChaptersResponseToJSON,
    VideoFromJSON,
    VideoToJSON,
    VideoUploadInitRequestFromJSON,
    VideoUploadInitRequestToJSON,
} from '../models/index';

export interface DeleteVideosVideoIdAudioTracksRequest {
    videoId: string;
}

export interface DeleteVideosVideoIdAudioTracksLangCodeRequest {
    videoId: string;
    langCode: string;
}

export interface DeleteVideosVideoIdAudioTracksTrackIdRequest {
    videoId: string;
    trackId: string;
}

export interface DeleteVideosVideoIdChaptersRequest {
    videoId: string;
}

export interface DeleteVideosVideoIdDeleteRequest {
    videoId: string;
}

export interface DeleteVideosVideoIdSubtitlesRequest {
    videoId: string;
}

export interface DeleteVideosVideoIdSubtitlesLangCodeRequest {
    videoId: string;
    langCode: string;
}

export interface DeleteVideosVideoIdSubtitlesSubtitleIdRequest {
    videoId: string;
    subtitleId: string;
}

export interface GetVideosRequest {
    limit?: number;
    offset?: number;
    sort?: string;
    order?: string;
}

export interface GetVideosVideoIdRequest {
    videoId: string;
}

export interface PostVideosUploadCompleteRequest {
    request: GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest;
}

export interface PostVideosUploadInitRequest {
    request: VideoUploadInitRequest;
}

export interface PostVideosVideoIdAudioTracksRequest {
    videoId: string;
    files: Array<Blob>;
    languageCodes: string;
    labels: string;
}

export interface PostVideosVideoIdSubtitlesRequest {
    videoId: string;
    files: Array<Blob>;
    languageCodes: string;
    labels: string;
}

export interface PutVideosVideoIdAudioTracksLangCodeRequest {
    videoId: string;
    langCode: string;
    file: Blob;
    label?: string;
}

export interface PutVideosVideoIdChaptersRequest {
    videoId: string;
    request: UpdateChaptersRequest;
}

export interface PutVideosVideoIdSubtitlesLangCodeRequest {
    videoId: string;
    langCode: string;
    file: Blob;
    label?: string;
}

export interface PutVideosVideoIdThumbnailRequest {
    videoId: string;
    thumbnail: Blob;
}

/**
 * 
 */
export class VideosApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteVideosVideoIdAudioTracks without sending the request
     */
    async deleteVideosVideoIdAudioTracksRequestOpts(requestParameters: DeleteVideosVideoIdAudioTracksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling deleteVideosVideoIdAudioTracks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/audio-tracks`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove all additional audio tracks from a video using API key authentication
     * Delete all audio tracks
     */
    async deleteVideosVideoIdAudioTracksRaw(requestParameters: DeleteVideosVideoIdAudioTracksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioTrackDelete>> {
        const requestOptions = await this.deleteVideosVideoIdAudioTracksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioTrackDeleteFromJSON(jsonValue));
    }

    /**
     * Remove all additional audio tracks from a video using API key authentication
     * Delete all audio tracks
     */
    async deleteVideosVideoIdAudioTracks(requestParameters: DeleteVideosVideoIdAudioTracksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioTrackDelete> {
        const response = await this.deleteVideosVideoIdAudioTracksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteVideosVideoIdAudioTracksLangCode without sending the request
     */
    async deleteVideosVideoIdAudioTracksLangCodeRequestOpts(requestParameters: DeleteVideosVideoIdAudioTracksLangCodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling deleteVideosVideoIdAudioTracksLangCode().'
            );
        }

        if (requestParameters['langCode'] == null) {
            throw new runtime.RequiredError(
                'langCode',
                'Required parameter "langCode" was null or undefined when calling deleteVideosVideoIdAudioTracksLangCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/audio-tracks/{lang_code}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"lang_code"}}`, encodeURIComponent(String(requestParameters['langCode'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove an audio track for a specific language using API key authentication
     * Delete audio track by language
     */
    async deleteVideosVideoIdAudioTracksLangCodeRaw(requestParameters: DeleteVideosVideoIdAudioTracksLangCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioTrackDelete>> {
        const requestOptions = await this.deleteVideosVideoIdAudioTracksLangCodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioTrackDeleteFromJSON(jsonValue));
    }

    /**
     * Remove an audio track for a specific language using API key authentication
     * Delete audio track by language
     */
    async deleteVideosVideoIdAudioTracksLangCode(requestParameters: DeleteVideosVideoIdAudioTracksLangCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioTrackDelete> {
        const response = await this.deleteVideosVideoIdAudioTracksLangCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteVideosVideoIdAudioTracksTrackId without sending the request
     */
    async deleteVideosVideoIdAudioTracksTrackIdRequestOpts(requestParameters: DeleteVideosVideoIdAudioTracksTrackIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling deleteVideosVideoIdAudioTracksTrackId().'
            );
        }

        if (requestParameters['trackId'] == null) {
            throw new runtime.RequiredError(
                'trackId',
                'Required parameter "trackId" was null or undefined when calling deleteVideosVideoIdAudioTracksTrackId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/audio-tracks/{trackId}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"trackId"}}`, encodeURIComponent(String(requestParameters['trackId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove an additional audio track from a video using API key authentication
     * Delete audio track
     */
    async deleteVideosVideoIdAudioTracksTrackIdRaw(requestParameters: DeleteVideosVideoIdAudioTracksTrackIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioTrackDelete>> {
        const requestOptions = await this.deleteVideosVideoIdAudioTracksTrackIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioTrackDeleteFromJSON(jsonValue));
    }

    /**
     * Remove an additional audio track from a video using API key authentication
     * Delete audio track
     */
    async deleteVideosVideoIdAudioTracksTrackId(requestParameters: DeleteVideosVideoIdAudioTracksTrackIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioTrackDelete> {
        const response = await this.deleteVideosVideoIdAudioTracksTrackIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteVideosVideoIdChapters without sending the request
     */
    async deleteVideosVideoIdChaptersRequestOpts(requestParameters: DeleteVideosVideoIdChaptersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling deleteVideosVideoIdChapters().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/chapters`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove all chapters from a video using API key authentication
     * Delete video chapters
     */
    async deleteVideosVideoIdChaptersRaw(requestParameters: DeleteVideosVideoIdChaptersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateChaptersResponse>> {
        const requestOptions = await this.deleteVideosVideoIdChaptersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateChaptersResponseFromJSON(jsonValue));
    }

    /**
     * Remove all chapters from a video using API key authentication
     * Delete video chapters
     */
    async deleteVideosVideoIdChapters(requestParameters: DeleteVideosVideoIdChaptersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateChaptersResponse> {
        const response = await this.deleteVideosVideoIdChaptersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteVideosVideoIdDelete without sending the request
     */
    async deleteVideosVideoIdDeleteRequestOpts(requestParameters: DeleteVideosVideoIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling deleteVideosVideoIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/delete`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a video by its ID within a project
     * Delete video
     */
    async deleteVideosVideoIdDeleteRaw(requestParameters: DeleteVideosVideoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteVideosVideoIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a video by its ID within a project
     * Delete video
     */
    async deleteVideosVideoIdDelete(requestParameters: DeleteVideosVideoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteVideosVideoIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteVideosVideoIdSubtitles without sending the request
     */
    async deleteVideosVideoIdSubtitlesRequestOpts(requestParameters: DeleteVideosVideoIdSubtitlesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling deleteVideosVideoIdSubtitles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/subtitles`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove all subtitles from a video using API key authentication
     * Delete all subtitles
     */
    async deleteVideosVideoIdSubtitlesRaw(requestParameters: DeleteVideosVideoIdSubtitlesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubtitleDelete>> {
        const requestOptions = await this.deleteVideosVideoIdSubtitlesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubtitleDeleteFromJSON(jsonValue));
    }

    /**
     * Remove all subtitles from a video using API key authentication
     * Delete all subtitles
     */
    async deleteVideosVideoIdSubtitles(requestParameters: DeleteVideosVideoIdSubtitlesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubtitleDelete> {
        const response = await this.deleteVideosVideoIdSubtitlesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteVideosVideoIdSubtitlesLangCode without sending the request
     */
    async deleteVideosVideoIdSubtitlesLangCodeRequestOpts(requestParameters: DeleteVideosVideoIdSubtitlesLangCodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling deleteVideosVideoIdSubtitlesLangCode().'
            );
        }

        if (requestParameters['langCode'] == null) {
            throw new runtime.RequiredError(
                'langCode',
                'Required parameter "langCode" was null or undefined when calling deleteVideosVideoIdSubtitlesLangCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/subtitles/{lang_code}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"lang_code"}}`, encodeURIComponent(String(requestParameters['langCode'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a subtitle for a specific language using API key authentication
     * Delete subtitle by language
     */
    async deleteVideosVideoIdSubtitlesLangCodeRaw(requestParameters: DeleteVideosVideoIdSubtitlesLangCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubtitleDelete>> {
        const requestOptions = await this.deleteVideosVideoIdSubtitlesLangCodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubtitleDeleteFromJSON(jsonValue));
    }

    /**
     * Remove a subtitle for a specific language using API key authentication
     * Delete subtitle by language
     */
    async deleteVideosVideoIdSubtitlesLangCode(requestParameters: DeleteVideosVideoIdSubtitlesLangCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubtitleDelete> {
        const response = await this.deleteVideosVideoIdSubtitlesLangCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteVideosVideoIdSubtitlesSubtitleId without sending the request
     */
    async deleteVideosVideoIdSubtitlesSubtitleIdRequestOpts(requestParameters: DeleteVideosVideoIdSubtitlesSubtitleIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling deleteVideosVideoIdSubtitlesSubtitleId().'
            );
        }

        if (requestParameters['subtitleId'] == null) {
            throw new runtime.RequiredError(
                'subtitleId',
                'Required parameter "subtitleId" was null or undefined when calling deleteVideosVideoIdSubtitlesSubtitleId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/subtitles/{subtitleId}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"subtitleId"}}`, encodeURIComponent(String(requestParameters['subtitleId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a subtitle from a video using API key authentication
     * Delete subtitle
     */
    async deleteVideosVideoIdSubtitlesSubtitleIdRaw(requestParameters: DeleteVideosVideoIdSubtitlesSubtitleIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubtitleDelete>> {
        const requestOptions = await this.deleteVideosVideoIdSubtitlesSubtitleIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubtitleDeleteFromJSON(jsonValue));
    }

    /**
     * Remove a subtitle from a video using API key authentication
     * Delete subtitle
     */
    async deleteVideosVideoIdSubtitlesSubtitleId(requestParameters: DeleteVideosVideoIdSubtitlesSubtitleIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubtitleDelete> {
        const response = await this.deleteVideosVideoIdSubtitlesSubtitleIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVideos without sending the request
     */
    async getVideosRequestOpts(requestParameters: GetVideosRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all videos for a specific project, with pagination and sorting.
     * List videos for a project
     */
    async getVideosRaw(requestParameters: GetVideosRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationPaginatedResponseVideo>> {
        const requestOptions = await this.getVideosRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginationPaginatedResponseVideoFromJSON(jsonValue));
    }

    /**
     * Retrieve all videos for a specific project, with pagination and sorting.
     * List videos for a project
     */
    async getVideos(requestParameters: GetVideosRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationPaginatedResponseVideo> {
        const response = await this.getVideosRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVideosLanguages without sending the request
     */
    async getVideosLanguagesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/videos/languages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of supported languages for subtitles
     * List available subtitle languages
     */
    async getVideosLanguagesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InternalVideosHandlerSubtitlesLanguageResponse>>> {
        const requestOptions = await this.getVideosLanguagesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InternalVideosHandlerSubtitlesLanguageResponseFromJSON));
    }

    /**
     * Get list of supported languages for subtitles
     * List available subtitle languages
     */
    async getVideosLanguages(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InternalVideosHandlerSubtitlesLanguageResponse>> {
        const response = await this.getVideosLanguagesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVideosVideoId without sending the request
     */
    async getVideosVideoIdRequestOpts(requestParameters: GetVideosVideoIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling getVideosVideoId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a video by its ID for a specific project.
     * Get a video
     */
    async getVideosVideoIdRaw(requestParameters: GetVideosVideoIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Video>> {
        const requestOptions = await this.getVideosVideoIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoFromJSON(jsonValue));
    }

    /**
     * Retrieve a video by its ID for a specific project.
     * Get a video
     */
    async getVideosVideoId(requestParameters: GetVideosVideoIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Video> {
        const response = await this.getVideosVideoIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postVideosUploadComplete without sending the request
     */
    async postVideosUploadCompleteRequestOpts(requestParameters: PostVideosUploadCompleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling postVideosUploadComplete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/upload/complete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Mark a video upload as complete after successful upload to storage using API key authentication
     * Upload: Mark as complete
     */
    async postVideosUploadCompleteRaw(requestParameters: PostVideosUploadCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Video>> {
        const requestOptions = await this.postVideosUploadCompleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoFromJSON(jsonValue));
    }

    /**
     * Mark a video upload as complete after successful upload to storage using API key authentication
     * Upload: Mark as complete
     */
    async postVideosUploadComplete(requestParameters: PostVideosUploadCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Video> {
        const response = await this.postVideosUploadCompleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postVideosUploadInit without sending the request
     */
    async postVideosUploadInitRequestOpts(requestParameters: PostVideosUploadInitRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling postVideosUploadInit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/upload/init`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideoUploadInitRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Initialize a video upload and get presigned URLs for video and poster using API key authentication
     * Upload: Init
     */
    async postVideosUploadInitRaw(requestParameters: PostVideosUploadInitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GithubComQeeqezApiInternalVideosHandlerUploadInitResponse>> {
        const requestOptions = await this.postVideosUploadInitRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GithubComQeeqezApiInternalVideosHandlerUploadInitResponseFromJSON(jsonValue));
    }

    /**
     * Initialize a video upload and get presigned URLs for video and poster using API key authentication
     * Upload: Init
     */
    async postVideosUploadInit(requestParameters: PostVideosUploadInitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GithubComQeeqezApiInternalVideosHandlerUploadInitResponse> {
        const response = await this.postVideosUploadInitRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postVideosVideoIdAudioTracks without sending the request
     */
    async postVideosVideoIdAudioTracksRequestOpts(requestParameters: PostVideosVideoIdAudioTracksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling postVideosVideoIdAudioTracks().'
            );
        }

        if (requestParameters['files'] == null) {
            throw new runtime.RequiredError(
                'files',
                'Required parameter "files" was null or undefined when calling postVideosVideoIdAudioTracks().'
            );
        }

        if (requestParameters['languageCodes'] == null) {
            throw new runtime.RequiredError(
                'languageCodes',
                'Required parameter "languageCodes" was null or undefined when calling postVideosVideoIdAudioTracks().'
            );
        }

        if (requestParameters['labels'] == null) {
            throw new runtime.RequiredError(
                'labels',
                'Required parameter "labels" was null or undefined when calling postVideosVideoIdAudioTracks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['files'] != null) {
            requestParameters['files'].forEach((element) => {
                formParams.append('files', element as any);
            })
        }

        if (requestParameters['languageCodes'] != null) {
            formParams.append('language_codes', requestParameters['languageCodes'] as any);
        }

        if (requestParameters['labels'] != null) {
            formParams.append('labels', requestParameters['labels'] as any);
        }


        let urlPath = `/videos/{videoId}/audio-tracks`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Replace all audio tracks with the provided ones using API key authentication
     * Bulk upsert video audio tracks
     */
    async postVideosVideoIdAudioTracksRaw(requestParameters: PostVideosVideoIdAudioTracksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AudioTrack>>> {
        const requestOptions = await this.postVideosVideoIdAudioTracksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AudioTrackFromJSON));
    }

    /**
     * Replace all audio tracks with the provided ones using API key authentication
     * Bulk upsert video audio tracks
     */
    async postVideosVideoIdAudioTracks(requestParameters: PostVideosVideoIdAudioTracksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AudioTrack>> {
        const response = await this.postVideosVideoIdAudioTracksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postVideosVideoIdSubtitles without sending the request
     */
    async postVideosVideoIdSubtitlesRequestOpts(requestParameters: PostVideosVideoIdSubtitlesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling postVideosVideoIdSubtitles().'
            );
        }

        if (requestParameters['files'] == null) {
            throw new runtime.RequiredError(
                'files',
                'Required parameter "files" was null or undefined when calling postVideosVideoIdSubtitles().'
            );
        }

        if (requestParameters['languageCodes'] == null) {
            throw new runtime.RequiredError(
                'languageCodes',
                'Required parameter "languageCodes" was null or undefined when calling postVideosVideoIdSubtitles().'
            );
        }

        if (requestParameters['labels'] == null) {
            throw new runtime.RequiredError(
                'labels',
                'Required parameter "labels" was null or undefined when calling postVideosVideoIdSubtitles().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['files'] != null) {
            requestParameters['files'].forEach((element) => {
                formParams.append('files', element as any);
            })
        }

        if (requestParameters['languageCodes'] != null) {
            formParams.append('language_codes', requestParameters['languageCodes'] as any);
        }

        if (requestParameters['labels'] != null) {
            formParams.append('labels', requestParameters['labels'] as any);
        }


        let urlPath = `/videos/{videoId}/subtitles`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Replace all subtitles with the provided ones using API key authentication
     * Bulk upsert video subtitles
     */
    async postVideosVideoIdSubtitlesRaw(requestParameters: PostVideosVideoIdSubtitlesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Subtitle>>> {
        const requestOptions = await this.postVideosVideoIdSubtitlesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SubtitleFromJSON));
    }

    /**
     * Replace all subtitles with the provided ones using API key authentication
     * Bulk upsert video subtitles
     */
    async postVideosVideoIdSubtitles(requestParameters: PostVideosVideoIdSubtitlesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Subtitle>> {
        const response = await this.postVideosVideoIdSubtitlesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putVideosVideoIdAudioTracksLangCode without sending the request
     */
    async putVideosVideoIdAudioTracksLangCodeRequestOpts(requestParameters: PutVideosVideoIdAudioTracksLangCodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling putVideosVideoIdAudioTracksLangCode().'
            );
        }

        if (requestParameters['langCode'] == null) {
            throw new runtime.RequiredError(
                'langCode',
                'Required parameter "langCode" was null or undefined when calling putVideosVideoIdAudioTracksLangCode().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling putVideosVideoIdAudioTracksLangCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['label'] != null) {
            formParams.append('label', requestParameters['label'] as any);
        }


        let urlPath = `/videos/{videoId}/audio-tracks/{lang_code}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"lang_code"}}`, encodeURIComponent(String(requestParameters['langCode'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Add or replace an audio track for a specific language using API key authentication
     * Upsert video audio track
     */
    async putVideosVideoIdAudioTracksLangCodeRaw(requestParameters: PutVideosVideoIdAudioTracksLangCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioTrack>> {
        const requestOptions = await this.putVideosVideoIdAudioTracksLangCodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioTrackFromJSON(jsonValue));
    }

    /**
     * Add or replace an audio track for a specific language using API key authentication
     * Upsert video audio track
     */
    async putVideosVideoIdAudioTracksLangCode(requestParameters: PutVideosVideoIdAudioTracksLangCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioTrack> {
        const response = await this.putVideosVideoIdAudioTracksLangCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putVideosVideoIdChapters without sending the request
     */
    async putVideosVideoIdChaptersRequestOpts(requestParameters: PutVideosVideoIdChaptersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling putVideosVideoIdChapters().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling putVideosVideoIdChapters().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/chapters`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateChaptersRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Replace all chapters for a video (atomic PUT operation) using API key authentication
     * Update video chapters
     */
    async putVideosVideoIdChaptersRaw(requestParameters: PutVideosVideoIdChaptersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateChaptersResponse>> {
        const requestOptions = await this.putVideosVideoIdChaptersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateChaptersResponseFromJSON(jsonValue));
    }

    /**
     * Replace all chapters for a video (atomic PUT operation) using API key authentication
     * Update video chapters
     */
    async putVideosVideoIdChapters(requestParameters: PutVideosVideoIdChaptersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateChaptersResponse> {
        const response = await this.putVideosVideoIdChaptersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putVideosVideoIdSubtitlesLangCode without sending the request
     */
    async putVideosVideoIdSubtitlesLangCodeRequestOpts(requestParameters: PutVideosVideoIdSubtitlesLangCodeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling putVideosVideoIdSubtitlesLangCode().'
            );
        }

        if (requestParameters['langCode'] == null) {
            throw new runtime.RequiredError(
                'langCode',
                'Required parameter "langCode" was null or undefined when calling putVideosVideoIdSubtitlesLangCode().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling putVideosVideoIdSubtitlesLangCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['label'] != null) {
            formParams.append('label', requestParameters['label'] as any);
        }


        let urlPath = `/videos/{videoId}/subtitles/{lang_code}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"lang_code"}}`, encodeURIComponent(String(requestParameters['langCode'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Add or replace a subtitle for a specific language using API key authentication
     * Upsert video subtitle
     */
    async putVideosVideoIdSubtitlesLangCodeRaw(requestParameters: PutVideosVideoIdSubtitlesLangCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Subtitle>> {
        const requestOptions = await this.putVideosVideoIdSubtitlesLangCodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubtitleFromJSON(jsonValue));
    }

    /**
     * Add or replace a subtitle for a specific language using API key authentication
     * Upsert video subtitle
     */
    async putVideosVideoIdSubtitlesLangCode(requestParameters: PutVideosVideoIdSubtitlesLangCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Subtitle> {
        const response = await this.putVideosVideoIdSubtitlesLangCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putVideosVideoIdThumbnail without sending the request
     */
    async putVideosVideoIdThumbnailRequestOpts(requestParameters: PutVideosVideoIdThumbnailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling putVideosVideoIdThumbnail().'
            );
        }

        if (requestParameters['thumbnail'] == null) {
            throw new runtime.RequiredError(
                'thumbnail',
                'Required parameter "thumbnail" was null or undefined when calling putVideosVideoIdThumbnail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['thumbnail'] != null) {
            formParams.append('thumbnail', requestParameters['thumbnail'] as any);
        }


        let urlPath = `/videos/{videoId}/thumbnail`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Update the thumbnail image for an existing video using API key authentication
     * Update video thumbnail
     */
    async putVideosVideoIdThumbnailRaw(requestParameters: PutVideosVideoIdThumbnailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Video>> {
        const requestOptions = await this.putVideosVideoIdThumbnailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoFromJSON(jsonValue));
    }

    /**
     * Update the thumbnail image for an existing video using API key authentication
     * Update video thumbnail
     */
    async putVideosVideoIdThumbnail(requestParameters: PutVideosVideoIdThumbnailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Video> {
        const response = await this.putVideosVideoIdThumbnailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
