/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AudioTrack,
  AudioTrackDelete,
  GithubComQeeqezApiInternalErrorsErrorResponse,
  GithubComQeeqezApiInternalVideosHandlerUploadInitResponse,
  InternalVideosHandlerSubtitlesLanguageResponse,
  PaginationPaginatedResponseVideo,
  Subtitle,
  SubtitleDelete,
  UpdateChaptersResponse,
  Video,
  VideosUploadCompletePostRequest,
  VideosUploadInitPostRequest,
  VideosVideoIdChaptersPutRequest,
} from '../models/index';
import {
    AudioTrackFromJSON,
    AudioTrackToJSON,
    AudioTrackDeleteFromJSON,
    AudioTrackDeleteToJSON,
    GithubComQeeqezApiInternalErrorsErrorResponseFromJSON,
    GithubComQeeqezApiInternalErrorsErrorResponseToJSON,
    GithubComQeeqezApiInternalVideosHandlerUploadInitResponseFromJSON,
    GithubComQeeqezApiInternalVideosHandlerUploadInitResponseToJSON,
    InternalVideosHandlerSubtitlesLanguageResponseFromJSON,
    InternalVideosHandlerSubtitlesLanguageResponseToJSON,
    PaginationPaginatedResponseVideoFromJSON,
    PaginationPaginatedResponseVideoToJSON,
    SubtitleFromJSON,
    SubtitleToJSON,
    SubtitleDeleteFromJSON,
    SubtitleDeleteToJSON,
    UpdateChaptersResponseFromJSON,
    UpdateChaptersResponseToJSON,
    VideoFromJSON,
    VideoToJSON,
    VideosUploadCompletePostRequestFromJSON,
    VideosUploadCompletePostRequestToJSON,
    VideosUploadInitPostRequestFromJSON,
    VideosUploadInitPostRequestToJSON,
    VideosVideoIdChaptersPutRequestFromJSON,
    VideosVideoIdChaptersPutRequestToJSON,
} from '../models/index';

export interface VideosGetRequest {
    limit?: number;
    offset?: number;
    sort?: string;
    order?: string;
}

export interface VideosUploadCompletePostOperationRequest {
    videosUploadCompletePostRequest: VideosUploadCompletePostRequest;
}

export interface VideosUploadInitPostOperationRequest {
    videosUploadInitPostRequest: VideosUploadInitPostRequest;
}

export interface VideosVideoIdAudioTracksDeleteRequest {
    videoId: string;
}

export interface VideosVideoIdAudioTracksLangCodeDeleteRequest {
    videoId: string;
    langCode: string;
}

export interface VideosVideoIdAudioTracksLangCodePutRequest {
    videoId: string;
    langCode: string;
}

export interface VideosVideoIdAudioTracksPostRequest {
    videoId: string;
}

export interface VideosVideoIdAudioTracksTrackIdDeleteRequest {
    videoId: string;
    trackId: string;
}

export interface VideosVideoIdChaptersDeleteRequest {
    videoId: string;
}

export interface VideosVideoIdChaptersPutOperationRequest {
    videoId: string;
    videosVideoIdChaptersPutRequest: VideosVideoIdChaptersPutRequest;
}

export interface VideosVideoIdDeleteDeleteRequest {
    videoId: string;
}

export interface VideosVideoIdGetRequest {
    videoId: string;
}

export interface VideosVideoIdSubtitlesDeleteRequest {
    videoId: string;
}

export interface VideosVideoIdSubtitlesLangCodeDeleteRequest {
    videoId: string;
    langCode: string;
}

export interface VideosVideoIdSubtitlesLangCodePutRequest {
    videoId: string;
    langCode: string;
}

export interface VideosVideoIdSubtitlesPostRequest {
    videoId: string;
}

export interface VideosVideoIdSubtitlesSubtitleIdDeleteRequest {
    videoId: string;
    subtitleId: string;
}

export interface VideosVideoIdThumbnailPutRequest {
    videoId: string;
}

/**
 * 
 */
export class VideosApi extends runtime.BaseAPI {

    /**
     * Creates request options for videosGet without sending the request
     */
    async videosGetRequestOpts(requestParameters: VideosGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all videos for a specific project, with pagination and sorting.
     * List videos for a project
     */
    async videosGetRaw(requestParameters: VideosGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationPaginatedResponseVideo>> {
        const requestOptions = await this.videosGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginationPaginatedResponseVideoFromJSON(jsonValue));
    }

    /**
     * Retrieve all videos for a specific project, with pagination and sorting.
     * List videos for a project
     */
    async videosGet(requestParameters: VideosGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationPaginatedResponseVideo> {
        const response = await this.videosGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosLanguagesGet without sending the request
     */
    async videosLanguagesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/videos/languages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get list of supported languages for subtitles
     * List available subtitle languages
     */
    async videosLanguagesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InternalVideosHandlerSubtitlesLanguageResponse>>> {
        const requestOptions = await this.videosLanguagesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InternalVideosHandlerSubtitlesLanguageResponseFromJSON));
    }

    /**
     * Get list of supported languages for subtitles
     * List available subtitle languages
     */
    async videosLanguagesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InternalVideosHandlerSubtitlesLanguageResponse>> {
        const response = await this.videosLanguagesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosUploadCompletePost without sending the request
     */
    async videosUploadCompletePostRequestOpts(requestParameters: VideosUploadCompletePostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videosUploadCompletePostRequest'] == null) {
            throw new runtime.RequiredError(
                'videosUploadCompletePostRequest',
                'Required parameter "videosUploadCompletePostRequest" was null or undefined when calling videosUploadCompletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/upload/complete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideosUploadCompletePostRequestToJSON(requestParameters['videosUploadCompletePostRequest']),
        };
    }

    /**
     * Mark a video upload as complete after successful upload to storage using API key authentication
     * Upload: Mark as complete
     */
    async videosUploadCompletePostRaw(requestParameters: VideosUploadCompletePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Video>> {
        const requestOptions = await this.videosUploadCompletePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoFromJSON(jsonValue));
    }

    /**
     * Mark a video upload as complete after successful upload to storage using API key authentication
     * Upload: Mark as complete
     */
    async videosUploadCompletePost(requestParameters: VideosUploadCompletePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Video> {
        const response = await this.videosUploadCompletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosUploadInitPost without sending the request
     */
    async videosUploadInitPostRequestOpts(requestParameters: VideosUploadInitPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videosUploadInitPostRequest'] == null) {
            throw new runtime.RequiredError(
                'videosUploadInitPostRequest',
                'Required parameter "videosUploadInitPostRequest" was null or undefined when calling videosUploadInitPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/upload/init`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideosUploadInitPostRequestToJSON(requestParameters['videosUploadInitPostRequest']),
        };
    }

    /**
     * Initialize a video upload and get presigned URLs for video and poster using API key authentication
     * Upload: Init
     */
    async videosUploadInitPostRaw(requestParameters: VideosUploadInitPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GithubComQeeqezApiInternalVideosHandlerUploadInitResponse>> {
        const requestOptions = await this.videosUploadInitPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GithubComQeeqezApiInternalVideosHandlerUploadInitResponseFromJSON(jsonValue));
    }

    /**
     * Initialize a video upload and get presigned URLs for video and poster using API key authentication
     * Upload: Init
     */
    async videosUploadInitPost(requestParameters: VideosUploadInitPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GithubComQeeqezApiInternalVideosHandlerUploadInitResponse> {
        const response = await this.videosUploadInitPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdAudioTracksDelete without sending the request
     */
    async videosVideoIdAudioTracksDeleteRequestOpts(requestParameters: VideosVideoIdAudioTracksDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdAudioTracksDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/audio-tracks`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove all additional audio tracks from a video using API key authentication
     * Delete all audio tracks
     */
    async videosVideoIdAudioTracksDeleteRaw(requestParameters: VideosVideoIdAudioTracksDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioTrackDelete>> {
        const requestOptions = await this.videosVideoIdAudioTracksDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioTrackDeleteFromJSON(jsonValue));
    }

    /**
     * Remove all additional audio tracks from a video using API key authentication
     * Delete all audio tracks
     */
    async videosVideoIdAudioTracksDelete(requestParameters: VideosVideoIdAudioTracksDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioTrackDelete> {
        const response = await this.videosVideoIdAudioTracksDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdAudioTracksLangCodeDelete without sending the request
     */
    async videosVideoIdAudioTracksLangCodeDeleteRequestOpts(requestParameters: VideosVideoIdAudioTracksLangCodeDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdAudioTracksLangCodeDelete().'
            );
        }

        if (requestParameters['langCode'] == null) {
            throw new runtime.RequiredError(
                'langCode',
                'Required parameter "langCode" was null or undefined when calling videosVideoIdAudioTracksLangCodeDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/audio-tracks/{lang_code}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"lang_code"}}`, encodeURIComponent(String(requestParameters['langCode'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove an audio track for a specific language using API key authentication
     * Delete audio track by language
     */
    async videosVideoIdAudioTracksLangCodeDeleteRaw(requestParameters: VideosVideoIdAudioTracksLangCodeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioTrackDelete>> {
        const requestOptions = await this.videosVideoIdAudioTracksLangCodeDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioTrackDeleteFromJSON(jsonValue));
    }

    /**
     * Remove an audio track for a specific language using API key authentication
     * Delete audio track by language
     */
    async videosVideoIdAudioTracksLangCodeDelete(requestParameters: VideosVideoIdAudioTracksLangCodeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioTrackDelete> {
        const response = await this.videosVideoIdAudioTracksLangCodeDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdAudioTracksLangCodePut without sending the request
     */
    async videosVideoIdAudioTracksLangCodePutRequestOpts(requestParameters: VideosVideoIdAudioTracksLangCodePutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdAudioTracksLangCodePut().'
            );
        }

        if (requestParameters['langCode'] == null) {
            throw new runtime.RequiredError(
                'langCode',
                'Required parameter "langCode" was null or undefined when calling videosVideoIdAudioTracksLangCodePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/audio-tracks/{lang_code}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"lang_code"}}`, encodeURIComponent(String(requestParameters['langCode'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Add or replace an audio track for a specific language using API key authentication
     * Upsert video audio track
     */
    async videosVideoIdAudioTracksLangCodePutRaw(requestParameters: VideosVideoIdAudioTracksLangCodePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioTrack>> {
        const requestOptions = await this.videosVideoIdAudioTracksLangCodePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioTrackFromJSON(jsonValue));
    }

    /**
     * Add or replace an audio track for a specific language using API key authentication
     * Upsert video audio track
     */
    async videosVideoIdAudioTracksLangCodePut(requestParameters: VideosVideoIdAudioTracksLangCodePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioTrack> {
        const response = await this.videosVideoIdAudioTracksLangCodePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdAudioTracksPost without sending the request
     */
    async videosVideoIdAudioTracksPostRequestOpts(requestParameters: VideosVideoIdAudioTracksPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdAudioTracksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/audio-tracks`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Replace all audio tracks with the provided ones using API key authentication
     * Bulk upsert video audio tracks
     */
    async videosVideoIdAudioTracksPostRaw(requestParameters: VideosVideoIdAudioTracksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AudioTrack>>> {
        const requestOptions = await this.videosVideoIdAudioTracksPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AudioTrackFromJSON));
    }

    /**
     * Replace all audio tracks with the provided ones using API key authentication
     * Bulk upsert video audio tracks
     */
    async videosVideoIdAudioTracksPost(requestParameters: VideosVideoIdAudioTracksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AudioTrack>> {
        const response = await this.videosVideoIdAudioTracksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdAudioTracksTrackIdDelete without sending the request
     */
    async videosVideoIdAudioTracksTrackIdDeleteRequestOpts(requestParameters: VideosVideoIdAudioTracksTrackIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdAudioTracksTrackIdDelete().'
            );
        }

        if (requestParameters['trackId'] == null) {
            throw new runtime.RequiredError(
                'trackId',
                'Required parameter "trackId" was null or undefined when calling videosVideoIdAudioTracksTrackIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/audio-tracks/{trackId}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"trackId"}}`, encodeURIComponent(String(requestParameters['trackId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove an additional audio track from a video using API key authentication
     * Delete audio track
     */
    async videosVideoIdAudioTracksTrackIdDeleteRaw(requestParameters: VideosVideoIdAudioTracksTrackIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioTrackDelete>> {
        const requestOptions = await this.videosVideoIdAudioTracksTrackIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioTrackDeleteFromJSON(jsonValue));
    }

    /**
     * Remove an additional audio track from a video using API key authentication
     * Delete audio track
     */
    async videosVideoIdAudioTracksTrackIdDelete(requestParameters: VideosVideoIdAudioTracksTrackIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioTrackDelete> {
        const response = await this.videosVideoIdAudioTracksTrackIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdChaptersDelete without sending the request
     */
    async videosVideoIdChaptersDeleteRequestOpts(requestParameters: VideosVideoIdChaptersDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdChaptersDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/chapters`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove all chapters from a video using API key authentication
     * Delete video chapters
     */
    async videosVideoIdChaptersDeleteRaw(requestParameters: VideosVideoIdChaptersDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateChaptersResponse>> {
        const requestOptions = await this.videosVideoIdChaptersDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateChaptersResponseFromJSON(jsonValue));
    }

    /**
     * Remove all chapters from a video using API key authentication
     * Delete video chapters
     */
    async videosVideoIdChaptersDelete(requestParameters: VideosVideoIdChaptersDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateChaptersResponse> {
        const response = await this.videosVideoIdChaptersDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdChaptersPut without sending the request
     */
    async videosVideoIdChaptersPutRequestOpts(requestParameters: VideosVideoIdChaptersPutOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdChaptersPut().'
            );
        }

        if (requestParameters['videosVideoIdChaptersPutRequest'] == null) {
            throw new runtime.RequiredError(
                'videosVideoIdChaptersPutRequest',
                'Required parameter "videosVideoIdChaptersPutRequest" was null or undefined when calling videosVideoIdChaptersPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/chapters`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VideosVideoIdChaptersPutRequestToJSON(requestParameters['videosVideoIdChaptersPutRequest']),
        };
    }

    /**
     * Replace all chapters for a video (atomic PUT operation) using API key authentication
     * Update video chapters
     */
    async videosVideoIdChaptersPutRaw(requestParameters: VideosVideoIdChaptersPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateChaptersResponse>> {
        const requestOptions = await this.videosVideoIdChaptersPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateChaptersResponseFromJSON(jsonValue));
    }

    /**
     * Replace all chapters for a video (atomic PUT operation) using API key authentication
     * Update video chapters
     */
    async videosVideoIdChaptersPut(requestParameters: VideosVideoIdChaptersPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateChaptersResponse> {
        const response = await this.videosVideoIdChaptersPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdDeleteDelete without sending the request
     */
    async videosVideoIdDeleteDeleteRequestOpts(requestParameters: VideosVideoIdDeleteDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/delete`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a video by its ID within a project
     * Delete video
     */
    async videosVideoIdDeleteDeleteRaw(requestParameters: VideosVideoIdDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.videosVideoIdDeleteDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a video by its ID within a project
     * Delete video
     */
    async videosVideoIdDeleteDelete(requestParameters: VideosVideoIdDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.videosVideoIdDeleteDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for videosVideoIdGet without sending the request
     */
    async videosVideoIdGetRequestOpts(requestParameters: VideosVideoIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a video by its ID for a specific project.
     * Get a video
     */
    async videosVideoIdGetRaw(requestParameters: VideosVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Video>> {
        const requestOptions = await this.videosVideoIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoFromJSON(jsonValue));
    }

    /**
     * Retrieve a video by its ID for a specific project.
     * Get a video
     */
    async videosVideoIdGet(requestParameters: VideosVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Video> {
        const response = await this.videosVideoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdSubtitlesDelete without sending the request
     */
    async videosVideoIdSubtitlesDeleteRequestOpts(requestParameters: VideosVideoIdSubtitlesDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdSubtitlesDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/subtitles`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove all subtitles from a video using API key authentication
     * Delete all subtitles
     */
    async videosVideoIdSubtitlesDeleteRaw(requestParameters: VideosVideoIdSubtitlesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubtitleDelete>> {
        const requestOptions = await this.videosVideoIdSubtitlesDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubtitleDeleteFromJSON(jsonValue));
    }

    /**
     * Remove all subtitles from a video using API key authentication
     * Delete all subtitles
     */
    async videosVideoIdSubtitlesDelete(requestParameters: VideosVideoIdSubtitlesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubtitleDelete> {
        const response = await this.videosVideoIdSubtitlesDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdSubtitlesLangCodeDelete without sending the request
     */
    async videosVideoIdSubtitlesLangCodeDeleteRequestOpts(requestParameters: VideosVideoIdSubtitlesLangCodeDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdSubtitlesLangCodeDelete().'
            );
        }

        if (requestParameters['langCode'] == null) {
            throw new runtime.RequiredError(
                'langCode',
                'Required parameter "langCode" was null or undefined when calling videosVideoIdSubtitlesLangCodeDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/subtitles/{lang_code}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"lang_code"}}`, encodeURIComponent(String(requestParameters['langCode'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a subtitle for a specific language using API key authentication
     * Delete subtitle by language
     */
    async videosVideoIdSubtitlesLangCodeDeleteRaw(requestParameters: VideosVideoIdSubtitlesLangCodeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubtitleDelete>> {
        const requestOptions = await this.videosVideoIdSubtitlesLangCodeDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubtitleDeleteFromJSON(jsonValue));
    }

    /**
     * Remove a subtitle for a specific language using API key authentication
     * Delete subtitle by language
     */
    async videosVideoIdSubtitlesLangCodeDelete(requestParameters: VideosVideoIdSubtitlesLangCodeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubtitleDelete> {
        const response = await this.videosVideoIdSubtitlesLangCodeDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdSubtitlesLangCodePut without sending the request
     */
    async videosVideoIdSubtitlesLangCodePutRequestOpts(requestParameters: VideosVideoIdSubtitlesLangCodePutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdSubtitlesLangCodePut().'
            );
        }

        if (requestParameters['langCode'] == null) {
            throw new runtime.RequiredError(
                'langCode',
                'Required parameter "langCode" was null or undefined when calling videosVideoIdSubtitlesLangCodePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/subtitles/{lang_code}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"lang_code"}}`, encodeURIComponent(String(requestParameters['langCode'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Add or replace a subtitle for a specific language using API key authentication
     * Upsert video subtitle
     */
    async videosVideoIdSubtitlesLangCodePutRaw(requestParameters: VideosVideoIdSubtitlesLangCodePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Subtitle>> {
        const requestOptions = await this.videosVideoIdSubtitlesLangCodePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubtitleFromJSON(jsonValue));
    }

    /**
     * Add or replace a subtitle for a specific language using API key authentication
     * Upsert video subtitle
     */
    async videosVideoIdSubtitlesLangCodePut(requestParameters: VideosVideoIdSubtitlesLangCodePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Subtitle> {
        const response = await this.videosVideoIdSubtitlesLangCodePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdSubtitlesPost without sending the request
     */
    async videosVideoIdSubtitlesPostRequestOpts(requestParameters: VideosVideoIdSubtitlesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdSubtitlesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/subtitles`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Replace all subtitles with the provided ones using API key authentication
     * Bulk upsert video subtitles
     */
    async videosVideoIdSubtitlesPostRaw(requestParameters: VideosVideoIdSubtitlesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Subtitle>>> {
        const requestOptions = await this.videosVideoIdSubtitlesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SubtitleFromJSON));
    }

    /**
     * Replace all subtitles with the provided ones using API key authentication
     * Bulk upsert video subtitles
     */
    async videosVideoIdSubtitlesPost(requestParameters: VideosVideoIdSubtitlesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Subtitle>> {
        const response = await this.videosVideoIdSubtitlesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdSubtitlesSubtitleIdDelete without sending the request
     */
    async videosVideoIdSubtitlesSubtitleIdDeleteRequestOpts(requestParameters: VideosVideoIdSubtitlesSubtitleIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdSubtitlesSubtitleIdDelete().'
            );
        }

        if (requestParameters['subtitleId'] == null) {
            throw new runtime.RequiredError(
                'subtitleId',
                'Required parameter "subtitleId" was null or undefined when calling videosVideoIdSubtitlesSubtitleIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/subtitles/{subtitleId}`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));
        urlPath = urlPath.replace(`{${"subtitleId"}}`, encodeURIComponent(String(requestParameters['subtitleId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a subtitle from a video using API key authentication
     * Delete subtitle
     */
    async videosVideoIdSubtitlesSubtitleIdDeleteRaw(requestParameters: VideosVideoIdSubtitlesSubtitleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubtitleDelete>> {
        const requestOptions = await this.videosVideoIdSubtitlesSubtitleIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubtitleDeleteFromJSON(jsonValue));
    }

    /**
     * Remove a subtitle from a video using API key authentication
     * Delete subtitle
     */
    async videosVideoIdSubtitlesSubtitleIdDelete(requestParameters: VideosVideoIdSubtitlesSubtitleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubtitleDelete> {
        const response = await this.videosVideoIdSubtitlesSubtitleIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for videosVideoIdThumbnailPut without sending the request
     */
    async videosVideoIdThumbnailPutRequestOpts(requestParameters: VideosVideoIdThumbnailPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videosVideoIdThumbnailPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/videos/{videoId}/thumbnail`;
        urlPath = urlPath.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Update the thumbnail image for an existing video using API key authentication
     * Update video thumbnail
     */
    async videosVideoIdThumbnailPutRaw(requestParameters: VideosVideoIdThumbnailPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Video>> {
        const requestOptions = await this.videosVideoIdThumbnailPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoFromJSON(jsonValue));
    }

    /**
     * Update the thumbnail image for an existing video using API key authentication
     * Update video thumbnail
     */
    async videosVideoIdThumbnailPut(requestParameters: VideosVideoIdThumbnailPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Video> {
        const response = await this.videosVideoIdThumbnailPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
