/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface ChapterInput extends AdditionalDataHolder, Parsable {
    /**
     * The start_time_sec property
     */
    startTimeSec?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ChapterInput}
 */
// @ts-ignore
export function createChapterInputFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChapterInput;
}
/**
 * The deserialization information for the current model
 * @param ChapterInput The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChapterInput(chapterInput: Partial<ChapterInput> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "start_time_sec": n => { chapterInput.startTimeSec = n.getNumberValue(); },
        "title": n => { chapterInput.title = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param ChapterInput The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChapterInput(writer: SerializationWriter, chapterInput: Partial<ChapterInput> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!chapterInput || isSerializingDerivedType) { return; }
    writer.writeNumberValue("start_time_sec", chapterInput.startTimeSec);
    writer.writeStringValue("title", chapterInput.title);
    writer.writeAdditionalData(chapterInput.additionalData);
}
/* tslint:enable */
/* eslint-enable */
