/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithFeedItemRequestBuilder, WithFeedItemRequestBuilderNavigationMetadata, WithFeedItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /feeds
 */
export interface FeedsRequestBuilder extends BaseRequestBuilder<FeedsRequestBuilder> {
    /**
     * Gets an item from the rixlSdk.feeds.item collection
     * @param feedId Feed ID
     * @returns {WithFeedItemRequestBuilder}
     */
     byFeedId(feedId: string) : WithFeedItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const FeedsRequestBuilderUriTemplate = "{+baseurl}/feeds";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FeedsRequestBuilderNavigationMetadata: Record<Exclude<keyof FeedsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byFeedId: {
        requestsMetadata: WithFeedItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithFeedItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["feedId"],
    },
};
/* tslint:enable */
/* eslint-enable */
