/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GithubComQeeqezApiInternalErrorsErrorResponse,
  Image,
  ImagesUploadCompletePostRequest,
  ImagesUploadInitPostRequest,
  InternalImagesHandlerInitResponse,
  PaginationPaginatedResponseImage,
} from '../models/index';
import {
    GithubComQeeqezApiInternalErrorsErrorResponseFromJSON,
    GithubComQeeqezApiInternalErrorsErrorResponseToJSON,
    ImageFromJSON,
    ImageToJSON,
    ImagesUploadCompletePostRequestFromJSON,
    ImagesUploadCompletePostRequestToJSON,
    ImagesUploadInitPostRequestFromJSON,
    ImagesUploadInitPostRequestToJSON,
    InternalImagesHandlerInitResponseFromJSON,
    InternalImagesHandlerInitResponseToJSON,
    PaginationPaginatedResponseImageFromJSON,
    PaginationPaginatedResponseImageToJSON,
} from '../models/index';

export interface ImagesGetRequest {
    limit?: number;
    offset?: number;
    sort?: string;
    order?: string;
}

export interface ImagesImageIdDeleteRequest {
    imageId: string;
}

export interface ImagesImageIdGetRequest {
    imageId: string;
}

export interface ImagesUploadCompletePostOperationRequest {
    imagesUploadCompletePostRequest: ImagesUploadCompletePostRequest;
}

export interface ImagesUploadInitPostOperationRequest {
    imagesUploadInitPostRequest: ImagesUploadInitPostRequest;
}

/**
 * 
 */
export class ImagesApi extends runtime.BaseAPI {

    /**
     * Creates request options for imagesGet without sending the request
     */
    async imagesGetRequestOpts(requestParameters: ImagesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/images`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all images for a specific project, with pagination and sorting.
     * List images for a project
     */
    async imagesGetRaw(requestParameters: ImagesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationPaginatedResponseImage>> {
        const requestOptions = await this.imagesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginationPaginatedResponseImageFromJSON(jsonValue));
    }

    /**
     * Retrieve all images for a specific project, with pagination and sorting.
     * List images for a project
     */
    async imagesGet(requestParameters: ImagesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationPaginatedResponseImage> {
        const response = await this.imagesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for imagesImageIdDelete without sending the request
     */
    async imagesImageIdDeleteRequestOpts(requestParameters: ImagesImageIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imageId'] == null) {
            throw new runtime.RequiredError(
                'imageId',
                'Required parameter "imageId" was null or undefined when calling imagesImageIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/images/{imageId}`;
        urlPath = urlPath.replace(`{${"imageId"}}`, encodeURIComponent(String(requestParameters['imageId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * delete an image by marking it as deleted
     * Delete image
     */
    async imagesImageIdDeleteRaw(requestParameters: ImagesImageIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.imagesImageIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete an image by marking it as deleted
     * Delete image
     */
    async imagesImageIdDelete(requestParameters: ImagesImageIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.imagesImageIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for imagesImageIdGet without sending the request
     */
    async imagesImageIdGetRequestOpts(requestParameters: ImagesImageIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imageId'] == null) {
            throw new runtime.RequiredError(
                'imageId',
                'Required parameter "imageId" was null or undefined when calling imagesImageIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/images/{imageId}`;
        urlPath = urlPath.replace(`{${"imageId"}}`, encodeURIComponent(String(requestParameters['imageId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve an image by its ID for a specific project.
     * Get image
     */
    async imagesImageIdGetRaw(requestParameters: ImagesImageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Image>> {
        const requestOptions = await this.imagesImageIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageFromJSON(jsonValue));
    }

    /**
     * Retrieve an image by its ID for a specific project.
     * Get image
     */
    async imagesImageIdGet(requestParameters: ImagesImageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Image> {
        const response = await this.imagesImageIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for imagesUploadCompletePost without sending the request
     */
    async imagesUploadCompletePostRequestOpts(requestParameters: ImagesUploadCompletePostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imagesUploadCompletePostRequest'] == null) {
            throw new runtime.RequiredError(
                'imagesUploadCompletePostRequest',
                'Required parameter "imagesUploadCompletePostRequest" was null or undefined when calling imagesUploadCompletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/images/upload/complete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImagesUploadCompletePostRequestToJSON(requestParameters['imagesUploadCompletePostRequest']),
        };
    }

    /**
     * Complete the upload process and create the image record using API key authentication
     * Upload: Mark as complete
     */
    async imagesUploadCompletePostRaw(requestParameters: ImagesUploadCompletePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Image>> {
        const requestOptions = await this.imagesUploadCompletePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageFromJSON(jsonValue));
    }

    /**
     * Complete the upload process and create the image record using API key authentication
     * Upload: Mark as complete
     */
    async imagesUploadCompletePost(requestParameters: ImagesUploadCompletePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Image> {
        const response = await this.imagesUploadCompletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for imagesUploadInitPost without sending the request
     */
    async imagesUploadInitPostRequestOpts(requestParameters: ImagesUploadInitPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imagesUploadInitPostRequest'] == null) {
            throw new runtime.RequiredError(
                'imagesUploadInitPostRequest',
                'Required parameter "imagesUploadInitPostRequest" was null or undefined when calling imagesUploadInitPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/images/upload/init`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImagesUploadInitPostRequestToJSON(requestParameters['imagesUploadInitPostRequest']),
        };
    }

    /**
     * Initialize a presigned URL upload for an image file using API key authentication
     * Upload: Init
     */
    async imagesUploadInitPostRaw(requestParameters: ImagesUploadInitPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalImagesHandlerInitResponse>> {
        const requestOptions = await this.imagesUploadInitPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalImagesHandlerInitResponseFromJSON(jsonValue));
    }

    /**
     * Initialize a presigned URL upload for an image file using API key authentication
     * Upload: Init
     */
    async imagesUploadInitPost(requestParameters: ImagesUploadInitPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalImagesHandlerInitResponse> {
        const response = await this.imagesUploadInitPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
