/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GithubComQeeqezApiInternalErrorsErrorResponse,
  Image,
  InternalImagesHandlerCompleteRequest,
  InternalImagesHandlerInitResponse,
  InternalImagesHandlerUploadInitRequest,
  PaginationPaginatedResponseImage,
} from '../models/index';
import {
    GithubComQeeqezApiInternalErrorsErrorResponseFromJSON,
    GithubComQeeqezApiInternalErrorsErrorResponseToJSON,
    ImageFromJSON,
    ImageToJSON,
    InternalImagesHandlerCompleteRequestFromJSON,
    InternalImagesHandlerCompleteRequestToJSON,
    InternalImagesHandlerInitResponseFromJSON,
    InternalImagesHandlerInitResponseToJSON,
    InternalImagesHandlerUploadInitRequestFromJSON,
    InternalImagesHandlerUploadInitRequestToJSON,
    PaginationPaginatedResponseImageFromJSON,
    PaginationPaginatedResponseImageToJSON,
} from '../models/index';

export interface DeleteImagesImageIdRequest {
    imageId: string;
}

export interface GetImagesRequest {
    limit?: number;
    offset?: number;
    sort?: string;
    order?: string;
}

export interface GetImagesImageIdRequest {
    imageId: string;
}

export interface PostImagesUploadCompleteRequest {
    request: InternalImagesHandlerCompleteRequest;
}

export interface PostImagesUploadInitRequest {
    request: InternalImagesHandlerUploadInitRequest;
}

/**
 * 
 */
export class ImagesApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteImagesImageId without sending the request
     */
    async deleteImagesImageIdRequestOpts(requestParameters: DeleteImagesImageIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imageId'] == null) {
            throw new runtime.RequiredError(
                'imageId',
                'Required parameter "imageId" was null or undefined when calling deleteImagesImageId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/images/{imageId}`;
        urlPath = urlPath.replace(`{${"imageId"}}`, encodeURIComponent(String(requestParameters['imageId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * delete an image by marking it as deleted
     * Delete image
     */
    async deleteImagesImageIdRaw(requestParameters: DeleteImagesImageIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteImagesImageIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete an image by marking it as deleted
     * Delete image
     */
    async deleteImagesImageId(requestParameters: DeleteImagesImageIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteImagesImageIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getImages without sending the request
     */
    async getImagesRequestOpts(requestParameters: GetImagesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/images`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all images for a specific project, with pagination and sorting.
     * List images for a project
     */
    async getImagesRaw(requestParameters: GetImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginationPaginatedResponseImage>> {
        const requestOptions = await this.getImagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginationPaginatedResponseImageFromJSON(jsonValue));
    }

    /**
     * Retrieve all images for a specific project, with pagination and sorting.
     * List images for a project
     */
    async getImages(requestParameters: GetImagesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginationPaginatedResponseImage> {
        const response = await this.getImagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getImagesImageId without sending the request
     */
    async getImagesImageIdRequestOpts(requestParameters: GetImagesImageIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imageId'] == null) {
            throw new runtime.RequiredError(
                'imageId',
                'Required parameter "imageId" was null or undefined when calling getImagesImageId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/images/{imageId}`;
        urlPath = urlPath.replace(`{${"imageId"}}`, encodeURIComponent(String(requestParameters['imageId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve an image by its ID for a specific project.
     * Get image
     */
    async getImagesImageIdRaw(requestParameters: GetImagesImageIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Image>> {
        const requestOptions = await this.getImagesImageIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageFromJSON(jsonValue));
    }

    /**
     * Retrieve an image by its ID for a specific project.
     * Get image
     */
    async getImagesImageId(requestParameters: GetImagesImageIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Image> {
        const response = await this.getImagesImageIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postImagesUploadComplete without sending the request
     */
    async postImagesUploadCompleteRequestOpts(requestParameters: PostImagesUploadCompleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling postImagesUploadComplete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/images/upload/complete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InternalImagesHandlerCompleteRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Complete the upload process and create the image record using API key authentication
     * Upload: Mark as complete
     */
    async postImagesUploadCompleteRaw(requestParameters: PostImagesUploadCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Image>> {
        const requestOptions = await this.postImagesUploadCompleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageFromJSON(jsonValue));
    }

    /**
     * Complete the upload process and create the image record using API key authentication
     * Upload: Mark as complete
     */
    async postImagesUploadComplete(requestParameters: PostImagesUploadCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Image> {
        const response = await this.postImagesUploadCompleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postImagesUploadInit without sending the request
     */
    async postImagesUploadInitRequestOpts(requestParameters: PostImagesUploadInitRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling postImagesUploadInit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/images/upload/init`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InternalImagesHandlerUploadInitRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Initialize a presigned URL upload for an image file using API key authentication
     * Upload: Init
     */
    async postImagesUploadInitRaw(requestParameters: PostImagesUploadInitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InternalImagesHandlerInitResponse>> {
        const requestOptions = await this.postImagesUploadInitRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InternalImagesHandlerInitResponseFromJSON(jsonValue));
    }

    /**
     * Initialize a presigned URL upload for an image file using API key authentication
     * Upload: Init
     */
    async postImagesUploadInit(requestParameters: PostImagesUploadInitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InternalImagesHandlerInitResponse> {
        const response = await this.postImagesUploadInitRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
