/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, type ErrorResponse } from '../../../models/github_com_qeeqez_api_internal_errors/index.js';
// @ts-ignore
import { createPostFromDiscriminatorValue, type Post } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /feeds/{feedId}/{postId}
 */
export interface WithPostItemRequestBuilder extends BaseRequestBuilder<WithPostItemRequestBuilder> {
    /**
     * Retrieve a post from feed by its ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Post>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Post | undefined>;
    /**
     * Retrieve a post from feed by its ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithPostItemRequestBuilderUriTemplate = "{+baseurl}/feeds/{feedId}/{postId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithPostItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithPostItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPostFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
