/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota

export type PlanType = (typeof PlanTypeObject)[keyof typeof PlanTypeObject];
export type VideoQuality = (typeof VideoQualityObject)[keyof typeof VideoQualityObject];
export const PlanTypeObject = {
    Free: "free",
    Pro: "pro",
    Custom: "custom",
    Pay_as_you_go: "pay_as_you_go",
} as const;
export const VideoQualityObject = {
    Basic: "basic",
    Shorts: "shorts",
    Pro: "pro",
} as const;
/* tslint:enable */
/* eslint-enable */
