/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Chapter
 */
export interface Chapter {
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    durationLabel?: string;
    /**
     * 
     * @type {number}
     * @memberof Chapter
     */
    endTimeSec?: number;
    /**
     * 
     * @type {number}
     * @memberof Chapter
     */
    startTimeSec?: number;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    title?: string;
}

/**
 * Check if a given object implements the Chapter interface.
 */
export function instanceOfChapter(value: object): value is Chapter {
    return true;
}

export function ChapterFromJSON(json: any): Chapter {
    return ChapterFromJSONTyped(json, false);
}

export function ChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Chapter {
    if (json == null) {
        return json;
    }
    return {
        
        'durationLabel': json['duration_label'] == null ? undefined : json['duration_label'],
        'endTimeSec': json['end_time_sec'] == null ? undefined : json['end_time_sec'],
        'startTimeSec': json['start_time_sec'] == null ? undefined : json['start_time_sec'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function ChapterToJSON(json: any): Chapter {
    return ChapterToJSONTyped(json, false);
}

export function ChapterToJSONTyped(value?: Chapter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration_label': value['durationLabel'],
        'end_time_sec': value['endTimeSec'],
        'start_time_sec': value['startTimeSec'],
        'title': value['title'],
    };
}

