/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GithubComQeeqezApiDbSqlcVideoQuality = {
    VideoQualityBasic: 'basic',
    VideoQualityShorts: 'shorts',
    VideoQualityPro: 'pro',
    Basic2: 'basic',
    Shorts2: 'shorts',
    Pro2: 'pro'
} as const;
export type GithubComQeeqezApiDbSqlcVideoQuality = typeof GithubComQeeqezApiDbSqlcVideoQuality[keyof typeof GithubComQeeqezApiDbSqlcVideoQuality];


export function instanceOfGithubComQeeqezApiDbSqlcVideoQuality(value: any): boolean {
    for (const key in GithubComQeeqezApiDbSqlcVideoQuality) {
        if (Object.prototype.hasOwnProperty.call(GithubComQeeqezApiDbSqlcVideoQuality, key)) {
            if (GithubComQeeqezApiDbSqlcVideoQuality[key as keyof typeof GithubComQeeqezApiDbSqlcVideoQuality] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GithubComQeeqezApiDbSqlcVideoQualityFromJSON(json: any): GithubComQeeqezApiDbSqlcVideoQuality {
    return GithubComQeeqezApiDbSqlcVideoQualityFromJSONTyped(json, false);
}

export function GithubComQeeqezApiDbSqlcVideoQualityFromJSONTyped(json: any, ignoreDiscriminator: boolean): GithubComQeeqezApiDbSqlcVideoQuality {
    return json as GithubComQeeqezApiDbSqlcVideoQuality;
}

export function GithubComQeeqezApiDbSqlcVideoQualityToJSON(value?: GithubComQeeqezApiDbSqlcVideoQuality | null): any {
    return value as any;
}

export function GithubComQeeqezApiDbSqlcVideoQualityToJSONTyped(value: any, ignoreDiscriminator: boolean): GithubComQeeqezApiDbSqlcVideoQuality {
    return value as GithubComQeeqezApiDbSqlcVideoQuality;
}

