/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PlanType, PlanTypeObject, VideoQuality, VideoQualityObject } from './github_com_qeeqez_api_db_sqlc/index.js';
// @ts-ignore
import { createChapterInputFromDiscriminatorValue, serializeChapterInput, type ChapterInput } from './github_com_qeeqez_api_internal_videos_types/index.js';
// @ts-ignore
import { createVideoResponseFromDiscriminatorValue, serializeVideoResponse, type VideoResponse } from './github_com_qeeqez_api_internal_videos/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AudioTrack extends AdditionalDataHolder, Parsable {
    /**
     * The created_at property
     */
    createdAt?: string | null;
    /**
     * The format property
     */
    format?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The label property
     */
    label?: string | null;
    /**
     * The language_code property
     */
    languageCode?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The size property
     */
    size?: number | null;
    /**
     * The url property
     */
    url?: string | null;
    /**
     * The video_id property
     */
    videoId?: string | null;
}
export interface AudioTrackDelete extends AdditionalDataHolder, Parsable {
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The status property
     */
    status?: string | null;
}
export interface Chapter extends AdditionalDataHolder, Parsable {
    /**
     * The duration_label property
     */
    durationLabel?: string | null;
    /**
     * The end_time_sec property
     */
    endTimeSec?: number | null;
    /**
     * The start_time_sec property
     */
    startTimeSec?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AudioTrackDelete}
 */
// @ts-ignore
export function createAudioTrackDeleteFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAudioTrackDelete;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AudioTrack}
 */
// @ts-ignore
export function createAudioTrackFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAudioTrack;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Chapter}
 */
// @ts-ignore
export function createChapterFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoChapter;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {File}
 */
// @ts-ignore
export function createFileFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFile;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Image}
 */
// @ts-ignore
export function createImageFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoImage;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Post}
 */
// @ts-ignore
export function createPostFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPost;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SubtitleDelete}
 */
// @ts-ignore
export function createSubtitleDeleteFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSubtitleDelete;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Subtitle}
 */
// @ts-ignore
export function createSubtitleFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSubtitle;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateChaptersRequest}
 */
// @ts-ignore
export function createUpdateChaptersRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateChaptersRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateChaptersResponse}
 */
// @ts-ignore
export function createUpdateChaptersResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateChaptersResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Video}
 */
// @ts-ignore
export function createVideoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoVideo;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {VideoUploadInitRequest}
 */
// @ts-ignore
export function createVideoUploadInitRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoVideoUploadInitRequest;
}
/**
 * The deserialization information for the current model
 * @param AudioTrack The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAudioTrack(audioTrack: Partial<AudioTrack> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "created_at": n => { audioTrack.createdAt = n.getStringValue(); },
        "format": n => { audioTrack.format = n.getStringValue(); },
        "id": n => { audioTrack.id = n.getStringValue(); },
        "label": n => { audioTrack.label = n.getStringValue(); },
        "language_code": n => { audioTrack.languageCode = n.getStringValue(); },
        "name": n => { audioTrack.name = n.getStringValue(); },
        "size": n => { audioTrack.size = n.getNumberValue(); },
        "url": n => { audioTrack.url = n.getStringValue(); },
        "video_id": n => { audioTrack.videoId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AudioTrackDelete The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAudioTrackDelete(audioTrackDelete: Partial<AudioTrackDelete> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { audioTrackDelete.message = n.getStringValue(); },
        "status": n => { audioTrackDelete.status = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Chapter The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoChapter(chapter: Partial<Chapter> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "duration_label": n => { chapter.durationLabel = n.getStringValue(); },
        "end_time_sec": n => { chapter.endTimeSec = n.getNumberValue(); },
        "start_time_sec": n => { chapter.startTimeSec = n.getNumberValue(); },
        "title": n => { chapter.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param File The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFile(file: Partial<File> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "created_at": n => { file.createdAt = n.getStringValue(); },
        "format": n => { file.format = n.getStringValue(); },
        "id": n => { file.id = n.getStringValue(); },
        "name": n => { file.name = n.getStringValue(); },
        "project_id": n => { file.projectId = n.getStringValue(); },
        "size": n => { file.size = n.getNumberValue(); },
        "status": n => { file.status = n.getEnumValue<FileStatus>(FileStatusObject); },
        "updated_at": n => { file.updatedAt = n.getStringValue(); },
        "url": n => { file.url = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Image The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoImage(image: Partial<Image> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "attached_to_video": n => { image.attachedToVideo = n.getBooleanValue(); },
        "file": n => { image.file = n.getObjectValue<File>(createFileFromDiscriminatorValue); },
        "height": n => { image.height = n.getNumberValue(); },
        "id": n => { image.id = n.getStringValue(); },
        "thumbhash": n => { image.thumbhash = n.getStringValue(); },
        "width": n => { image.width = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Post The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPost(post: Partial<Post> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "created_at": n => { post.createdAt = n.getStringValue(); },
        "creator_id": n => { post.creatorId = n.getStringValue(); },
        "description": n => { post.description = n.getStringValue(); },
        "feed_id": n => { post.feedId = n.getStringValue(); },
        "id": n => { post.id = n.getStringValue(); },
        "image": n => { post.image = n.getObjectValue<Image>(createImageFromDiscriminatorValue); },
        "plan_type": n => { post.planType = n.getEnumValue<PlanType>(PlanTypeObject); },
        "type": n => { post.type = n.getEnumValue<PostType>(PostTypeObject); },
        "updated_at": n => { post.updatedAt = n.getStringValue(); },
        "video": n => { post.video = n.getObjectValue<VideoResponse>(createVideoResponseFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param Subtitle The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSubtitle(subtitle: Partial<Subtitle> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "created_at": n => { subtitle.createdAt = n.getStringValue(); },
        "id": n => { subtitle.id = n.getStringValue(); },
        "label": n => { subtitle.label = n.getStringValue(); },
        "language_code": n => { subtitle.languageCode = n.getStringValue(); },
        "name": n => { subtitle.name = n.getStringValue(); },
        "size": n => { subtitle.size = n.getNumberValue(); },
        "url": n => { subtitle.url = n.getStringValue(); },
        "video_id": n => { subtitle.videoId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SubtitleDelete The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSubtitleDelete(subtitleDelete: Partial<SubtitleDelete> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { subtitleDelete.message = n.getStringValue(); },
        "status": n => { subtitleDelete.status = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateChaptersRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateChaptersRequest(updateChaptersRequest: Partial<UpdateChaptersRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "chapters": n => { updateChaptersRequest.chapters = n.getCollectionOfObjectValues<ChapterInput>(createChapterInputFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateChaptersResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateChaptersResponse(updateChaptersResponse: Partial<UpdateChaptersResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "chapters": n => { updateChaptersResponse.chapters = n.getCollectionOfObjectValues<Chapter>(createChapterFromDiscriminatorValue); },
        "video_id": n => { updateChaptersResponse.videoId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Video The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoVideo(video: Partial<Video> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "bitrate": n => { video.bitrate = n.getNumberValue(); },
        "chapters": n => { video.chapters = n.getCollectionOfObjectValues<Chapter>(createChapterFromDiscriminatorValue); },
        "codec": n => { video.codec = n.getStringValue(); },
        "duration": n => { video.duration = n.getNumberValue(); },
        "file": n => { video.file = n.getObjectValue<File>(createFileFromDiscriminatorValue); },
        "framerate": n => { video.framerate = n.getStringValue(); },
        "hdr": n => { video.hdr = n.getBooleanValue(); },
        "height": n => { video.height = n.getNumberValue(); },
        "id": n => { video.id = n.getStringValue(); },
        "plan_type": n => { video.planType = n.getEnumValue<PlanType>(PlanTypeObject); },
        "poster": n => { video.poster = n.getObjectValue<Image>(createImageFromDiscriminatorValue); },
        "width": n => { video.width = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param VideoUploadInitRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoVideoUploadInitRequest(videoUploadInitRequest: Partial<VideoUploadInitRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "file_name": n => { videoUploadInitRequest.fileName = n.getStringValue(); },
        "image_format": n => { videoUploadInitRequest.imageFormat = n.getStringValue(); },
        "video_quality": n => { videoUploadInitRequest.videoQuality = n.getEnumValue<VideoQuality>(VideoQualityObject); },
    }
}
export interface File extends AdditionalDataHolder, Parsable {
    /**
     * The created_at property
     */
    createdAt?: string | null;
    /**
     * The format property
     */
    format?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The project_id property
     */
    projectId?: string | null;
    /**
     * The size property
     */
    size?: number | null;
    /**
     * The status property
     */
    status?: FileStatus | null;
    /**
     * The updated_at property
     */
    updatedAt?: string | null;
    /**
     * The url property
     */
    url?: string | null;
}
export type FileStatus = (typeof FileStatusObject)[keyof typeof FileStatusObject];
export interface Image extends AdditionalDataHolder, Parsable {
    /**
     * The attached_to_video property
     */
    attachedToVideo?: boolean | null;
    /**
     * The file property
     */
    file?: File | null;
    /**
     * The height property
     */
    height?: number | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The thumbhash property
     */
    thumbhash?: string | null;
    /**
     * The width property
     */
    width?: number | null;
}
export interface Post extends AdditionalDataHolder, Parsable {
    /**
     * The created_at property
     */
    createdAt?: string | null;
    /**
     * The creator_id property
     */
    creatorId?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The feed_id property
     */
    feedId?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The image property
     */
    image?: Image | null;
    /**
     * The plan_type property
     */
    planType?: PlanType | null;
    /**
     * The type property
     */
    type?: PostType | null;
    /**
     * The updated_at property
     */
    updatedAt?: string | null;
    /**
     * The video property
     */
    video?: VideoResponse | null;
}
export type PostType = (typeof PostTypeObject)[keyof typeof PostTypeObject];
/**
 * Serializes information the current object
 * @param AudioTrack The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAudioTrack(writer: SerializationWriter, audioTrack: Partial<AudioTrack> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!audioTrack || isSerializingDerivedType) { return; }
    writer.writeStringValue("created_at", audioTrack.createdAt);
    writer.writeStringValue("format", audioTrack.format);
    writer.writeStringValue("id", audioTrack.id);
    writer.writeStringValue("label", audioTrack.label);
    writer.writeStringValue("language_code", audioTrack.languageCode);
    writer.writeStringValue("name", audioTrack.name);
    writer.writeNumberValue("size", audioTrack.size);
    writer.writeStringValue("url", audioTrack.url);
    writer.writeStringValue("video_id", audioTrack.videoId);
    writer.writeAdditionalData(audioTrack.additionalData);
}
/**
 * Serializes information the current object
 * @param AudioTrackDelete The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAudioTrackDelete(writer: SerializationWriter, audioTrackDelete: Partial<AudioTrackDelete> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!audioTrackDelete || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", audioTrackDelete.message);
    writer.writeStringValue("status", audioTrackDelete.status);
    writer.writeAdditionalData(audioTrackDelete.additionalData);
}
/**
 * Serializes information the current object
 * @param Chapter The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeChapter(writer: SerializationWriter, chapter: Partial<Chapter> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!chapter || isSerializingDerivedType) { return; }
    writer.writeStringValue("duration_label", chapter.durationLabel);
    writer.writeNumberValue("end_time_sec", chapter.endTimeSec);
    writer.writeNumberValue("start_time_sec", chapter.startTimeSec);
    writer.writeStringValue("title", chapter.title);
    writer.writeAdditionalData(chapter.additionalData);
}
/**
 * Serializes information the current object
 * @param File The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFile(writer: SerializationWriter, file: Partial<File> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!file || isSerializingDerivedType) { return; }
    writer.writeStringValue("created_at", file.createdAt);
    writer.writeStringValue("format", file.format);
    writer.writeStringValue("id", file.id);
    writer.writeStringValue("name", file.name);
    writer.writeStringValue("project_id", file.projectId);
    writer.writeNumberValue("size", file.size);
    writer.writeEnumValue<FileStatus>("status", file.status);
    writer.writeStringValue("updated_at", file.updatedAt);
    writer.writeStringValue("url", file.url);
    writer.writeAdditionalData(file.additionalData);
}
/**
 * Serializes information the current object
 * @param Image The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeImage(writer: SerializationWriter, image: Partial<Image> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!image || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("attached_to_video", image.attachedToVideo);
    writer.writeObjectValue<File>("file", image.file, serializeFile);
    writer.writeNumberValue("height", image.height);
    writer.writeStringValue("id", image.id);
    writer.writeStringValue("thumbhash", image.thumbhash);
    writer.writeNumberValue("width", image.width);
    writer.writeAdditionalData(image.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Post The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePost(writer: SerializationWriter, post: Partial<Post> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!post || isSerializingDerivedType) { return; }
    writer.writeStringValue("created_at", post.createdAt);
    writer.writeStringValue("creator_id", post.creatorId);
    writer.writeStringValue("description", post.description);
    writer.writeStringValue("feed_id", post.feedId);
    writer.writeStringValue("id", post.id);
    writer.writeObjectValue<Image>("image", post.image, serializeImage);
    writer.writeEnumValue<PlanType>("plan_type", post.planType);
    writer.writeEnumValue<PostType>("type", post.type);
    writer.writeStringValue("updated_at", post.updatedAt);
    writer.writeObjectValue<VideoResponse>("video", post.video, serializeVideoResponse);
    writer.writeAdditionalData(post.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Subtitle The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSubtitle(writer: SerializationWriter, subtitle: Partial<Subtitle> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!subtitle || isSerializingDerivedType) { return; }
    writer.writeStringValue("created_at", subtitle.createdAt);
    writer.writeStringValue("id", subtitle.id);
    writer.writeStringValue("label", subtitle.label);
    writer.writeStringValue("language_code", subtitle.languageCode);
    writer.writeStringValue("name", subtitle.name);
    writer.writeNumberValue("size", subtitle.size);
    writer.writeStringValue("url", subtitle.url);
    writer.writeStringValue("video_id", subtitle.videoId);
    writer.writeAdditionalData(subtitle.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SubtitleDelete The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSubtitleDelete(writer: SerializationWriter, subtitleDelete: Partial<SubtitleDelete> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!subtitleDelete || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", subtitleDelete.message);
    writer.writeStringValue("status", subtitleDelete.status);
    writer.writeAdditionalData(subtitleDelete.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateChaptersRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateChaptersRequest(writer: SerializationWriter, updateChaptersRequest: Partial<UpdateChaptersRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateChaptersRequest || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<ChapterInput>("chapters", updateChaptersRequest.chapters, serializeChapterInput);
    writer.writeAdditionalData(updateChaptersRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateChaptersResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateChaptersResponse(writer: SerializationWriter, updateChaptersResponse: Partial<UpdateChaptersResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateChaptersResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Chapter>("chapters", updateChaptersResponse.chapters, serializeChapter);
    writer.writeStringValue("video_id", updateChaptersResponse.videoId);
    writer.writeAdditionalData(updateChaptersResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Video The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeVideo(writer: SerializationWriter, video: Partial<Video> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!video || isSerializingDerivedType) { return; }
    writer.writeNumberValue("bitrate", video.bitrate);
    writer.writeCollectionOfObjectValues<Chapter>("chapters", video.chapters, serializeChapter);
    writer.writeStringValue("codec", video.codec);
    writer.writeNumberValue("duration", video.duration);
    writer.writeObjectValue<File>("file", video.file, serializeFile);
    writer.writeStringValue("framerate", video.framerate);
    writer.writeBooleanValue("hdr", video.hdr);
    writer.writeNumberValue("height", video.height);
    writer.writeStringValue("id", video.id);
    writer.writeEnumValue<PlanType>("plan_type", video.planType);
    writer.writeObjectValue<Image>("poster", video.poster, serializeImage);
    writer.writeNumberValue("width", video.width);
    writer.writeAdditionalData(video.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param VideoUploadInitRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeVideoUploadInitRequest(writer: SerializationWriter, videoUploadInitRequest: Partial<VideoUploadInitRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!videoUploadInitRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("file_name", videoUploadInitRequest.fileName);
    writer.writeStringValue("image_format", videoUploadInitRequest.imageFormat);
    writer.writeEnumValue<VideoQuality>("video_quality", videoUploadInitRequest.videoQuality);
    writer.writeAdditionalData(videoUploadInitRequest.additionalData);
}
export interface Subtitle extends AdditionalDataHolder, Parsable {
    /**
     * The created_at property
     */
    createdAt?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The label property
     */
    label?: string | null;
    /**
     * The language_code property
     */
    languageCode?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The size property
     */
    size?: number | null;
    /**
     * The url property
     */
    url?: string | null;
    /**
     * The video_id property
     */
    videoId?: string | null;
}
export interface SubtitleDelete extends AdditionalDataHolder, Parsable {
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The status property
     */
    status?: string | null;
}
/**
 * Chapters array
 */
export interface UpdateChaptersRequest extends AdditionalDataHolder, Parsable {
    /**
     * The chapters property
     */
    chapters?: ChapterInput[] | null;
}
export interface UpdateChaptersResponse extends AdditionalDataHolder, Parsable {
    /**
     * The chapters property
     */
    chapters?: Chapter[] | null;
    /**
     * The video_id property
     */
    videoId?: string | null;
}
export interface Video extends AdditionalDataHolder, Parsable {
    /**
     * The bitrate property
     */
    bitrate?: number | null;
    /**
     * The chapters property
     */
    chapters?: Chapter[] | null;
    /**
     * The codec property
     */
    codec?: string | null;
    /**
     * The duration property
     */
    duration?: number | null;
    /**
     * The file property
     */
    file?: File | null;
    /**
     * The framerate property
     */
    framerate?: string | null;
    /**
     * The hdr property
     */
    hdr?: boolean | null;
    /**
     * The height property
     */
    height?: number | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The plan_type property
     */
    planType?: PlanType | null;
    /**
     * The poster property
     */
    poster?: Image | null;
    /**
     * The width property
     */
    width?: number | null;
}
/**
 * Video upload initialization request
 */
export interface VideoUploadInitRequest extends AdditionalDataHolder, Parsable {
    /**
     * The file_name property
     */
    fileName?: string | null;
    /**
     * The image_format property
     */
    imageFormat?: string | null;
    /**
     * The video_quality property
     */
    videoQuality?: VideoQuality | null;
}
export const FileStatusObject = {
    Uploading: "uploading",
    Uploaded: "uploaded",
    Processing: "processing",
    Preparing: "preparing",
    Ready: "ready",
    ErrorEscaped: "error",
} as const;
export const PostTypeObject = {
    Image: "image",
    Video: "video",
} as const;
/* tslint:enable */
/* eslint-enable */
