/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalVideosHandlerSubtitlesLanguageResponse
 */
export interface InternalVideosHandlerSubtitlesLanguageResponse {
    /**
     * 
     * @type {string}
     * @memberof InternalVideosHandlerSubtitlesLanguageResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalVideosHandlerSubtitlesLanguageResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the InternalVideosHandlerSubtitlesLanguageResponse interface.
 */
export function instanceOfInternalVideosHandlerSubtitlesLanguageResponse(value: object): value is InternalVideosHandlerSubtitlesLanguageResponse {
    return true;
}

export function InternalVideosHandlerSubtitlesLanguageResponseFromJSON(json: any): InternalVideosHandlerSubtitlesLanguageResponse {
    return InternalVideosHandlerSubtitlesLanguageResponseFromJSONTyped(json, false);
}

export function InternalVideosHandlerSubtitlesLanguageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalVideosHandlerSubtitlesLanguageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function InternalVideosHandlerSubtitlesLanguageResponseToJSON(json: any): InternalVideosHandlerSubtitlesLanguageResponse {
    return InternalVideosHandlerSubtitlesLanguageResponseToJSONTyped(json, false);
}

export function InternalVideosHandlerSubtitlesLanguageResponseToJSONTyped(value?: InternalVideosHandlerSubtitlesLanguageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
    };
}

