/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalImagesHandlerUploadInitRequest
 */
export interface InternalImagesHandlerUploadInitRequest {
    /**
     * 
     * @type {string}
     * @memberof InternalImagesHandlerUploadInitRequest
     */
    format?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalImagesHandlerUploadInitRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the InternalImagesHandlerUploadInitRequest interface.
 */
export function instanceOfInternalImagesHandlerUploadInitRequest(value: object): value is InternalImagesHandlerUploadInitRequest {
    return true;
}

export function InternalImagesHandlerUploadInitRequestFromJSON(json: any): InternalImagesHandlerUploadInitRequest {
    return InternalImagesHandlerUploadInitRequestFromJSONTyped(json, false);
}

export function InternalImagesHandlerUploadInitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalImagesHandlerUploadInitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'format': json['format'] == null ? undefined : json['format'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function InternalImagesHandlerUploadInitRequestToJSON(json: any): InternalImagesHandlerUploadInitRequest {
    return InternalImagesHandlerUploadInitRequestToJSONTyped(json, false);
}

export function InternalImagesHandlerUploadInitRequestToJSONTyped(value?: InternalImagesHandlerUploadInitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'format': value['format'],
        'name': value['name'],
    };
}

