/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationPagination } from './PaginationPagination';
import {
    PaginationPaginationFromJSON,
    PaginationPaginationFromJSONTyped,
    PaginationPaginationToJSON,
    PaginationPaginationToJSONTyped,
} from './PaginationPagination';
import type { Post } from './Post';
import {
    PostFromJSON,
    PostFromJSONTyped,
    PostToJSON,
    PostToJSONTyped,
} from './Post';

/**
 * 
 * @export
 * @interface PaginationPaginatedResponsePost
 */
export interface PaginationPaginatedResponsePost {
    /**
     * Data contains the slice of items for the current request.
     * @type {Array<Post>}
     * @memberof PaginationPaginatedResponsePost
     */
    data?: Array<Post>;
    /**
     * 
     * @type {PaginationPagination}
     * @memberof PaginationPaginatedResponsePost
     */
    pagination?: PaginationPagination;
}

/**
 * Check if a given object implements the PaginationPaginatedResponsePost interface.
 */
export function instanceOfPaginationPaginatedResponsePost(value: object): value is PaginationPaginatedResponsePost {
    return true;
}

export function PaginationPaginatedResponsePostFromJSON(json: any): PaginationPaginatedResponsePost {
    return PaginationPaginatedResponsePostFromJSONTyped(json, false);
}

export function PaginationPaginatedResponsePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationPaginatedResponsePost {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PostFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationPaginationFromJSON(json['pagination']),
    };
}

export function PaginationPaginatedResponsePostToJSON(json: any): PaginationPaginatedResponsePost {
    return PaginationPaginatedResponsePostToJSONTyped(json, false);
}

export function PaginationPaginatedResponsePostToJSONTyped(value?: PaginationPaginatedResponsePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PostToJSON)),
        'pagination': PaginationPaginationToJSON(value['pagination']),
    };
}

