/* tslint:disable */
/* eslint-disable */
/**
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don\'t have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Subtitle
 */
export interface Subtitle {
    /**
     * 
     * @type {string}
     * @memberof Subtitle
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Subtitle
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Subtitle
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof Subtitle
     */
    languageCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Subtitle
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Subtitle
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof Subtitle
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Subtitle
     */
    videoId?: string;
}

/**
 * Check if a given object implements the Subtitle interface.
 */
export function instanceOfSubtitle(value: object): value is Subtitle {
    return true;
}

export function SubtitleFromJSON(json: any): Subtitle {
    return SubtitleFromJSONTyped(json, false);
}

export function SubtitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subtitle {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'] == null ? undefined : json['label'],
        'languageCode': json['language_code'] == null ? undefined : json['language_code'],
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'url': json['url'] == null ? undefined : json['url'],
        'videoId': json['video_id'] == null ? undefined : json['video_id'],
    };
}

export function SubtitleToJSON(json: any): Subtitle {
    return SubtitleToJSONTyped(json, false);
}

export function SubtitleToJSONTyped(value?: Subtitle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'id': value['id'],
        'label': value['label'],
        'language_code': value['languageCode'],
        'name': value['name'],
        'size': value['size'],
        'url': value['url'],
        'video_id': value['videoId'],
    };
}

