/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LanguageResponse}
 */
// @ts-ignore
export function createLanguageResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLanguageResponse;
}
/**
 * The deserialization information for the current model
 * @param LanguageResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLanguageResponse(languageResponse: Partial<LanguageResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { languageResponse.code = n.getStringValue(); },
        "name": n => { languageResponse.name = n.getStringValue(); },
    }
}
export interface LanguageResponse extends AdditionalDataHolder, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LanguageResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLanguageResponse(writer: SerializationWriter, languageResponse: Partial<LanguageResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!languageResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", languageResponse.code);
    writer.writeStringValue("name", languageResponse.name);
    writer.writeAdditionalData(languageResponse.additionalData);
}
/* tslint:enable */
/* eslint-enable */
