/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, type ErrorResponse } from '../models/github_com_qeeqez_api_internal_errors/index.js';
// @ts-ignore
import { createPaginatedResponseImageFromDiscriminatorValue, type PaginatedResponseImage } from '../models/pagination/index.js';
// @ts-ignore
import { type WithImageItemRequestBuilder, WithImageItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type UploadRequestBuilder, UploadRequestBuilderNavigationMetadata } from './upload/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /images
 */
export interface ImagesRequestBuilder extends BaseRequestBuilder<ImagesRequestBuilder> {
    /**
     * The upload property
     */
    get upload(): UploadRequestBuilder;
    /**
     * Gets an item from the rixlSdk.images.item collection
     * @param imageId Image ID
     * @returns {WithImageItemRequestBuilder}
     */
     byImageId(imageId: string) : WithImageItemRequestBuilder;
    /**
     * Retrieve all images for a specific project, with pagination and sorting.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PaginatedResponseImage>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 403 status code
     * @throws {ErrorResponse} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<ImagesRequestBuilderGetQueryParameters> | undefined) : Promise<PaginatedResponseImage | undefined>;
    /**
     * Retrieve all images for a specific project, with pagination and sorting.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ImagesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve all images for a specific project, with pagination and sorting.
 */
export interface ImagesRequestBuilderGetQueryParameters {
    /**
     * Maximum number of items to return in a single request. <br> **Default:** `25`
     */
    limit?: number;
    /**
     * Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
     */
    offset?: number;
    /**
     * Sort order (asc, desc)
     */
    order?: string;
    /**
     * Field to sort by (created_at, name, size, updated_at)
     */
    sort?: string;
}
/**
 * Uri template for the request builder.
 */
export const ImagesRequestBuilderUriTemplate = "{+baseurl}/images{?limit*,offset*,order*,sort*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ImagesRequestBuilderNavigationMetadata: Record<Exclude<keyof ImagesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byImageId: {
        requestsMetadata: WithImageItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["imageId"],
    },
    upload: {
        navigationMetadata: UploadRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ImagesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ImagesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPaginatedResponseImageFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
